IF DB_ID('$(DB_NAME)') IS NULL
BEGIN
    CREATE DATABASE [$(DB_NAME)];
END
GO


IF NOT EXISTS (
    SELECT 1
    FROM sys.server_principals
    WHERE name = '$(DB_USER)'
)
BEGIN
    CREATE LOGIN [$(DB_USER)]
    WITH PASSWORD = '$(DB_PASSWORD)';
END
GO


USE [$(DB_NAME)];
GO


IF NOT EXISTS (
    SELECT 1
    FROM sys.database_principals
    WHERE name = '$(DB_USER)'
)
BEGIN
    CREATE USER [$(DB_USER)]
    FOR LOGIN [$(DB_USER)];

    ALTER ROLE db_datareader ADD MEMBER [$(DB_USER)];
    ALTER ROLE db_datawriter ADD MEMBER [$(DB_USER)];
END
GO


IF OBJECT_ID('Cuisines', 'U') IS NULL
BEGIN
    CREATE TABLE Cuisines
    (
        id INT IDENTITY(1,1) PRIMARY KEY,
        cuisine_type VARCHAR(50) NOT NULL
    );
END
GO


IF OBJECT_ID('Restaurants', 'U') IS NULL
BEGIN
    CREATE TABLE Restaurants
    (
        id INT IDENTITY(1,1) PRIMARY KEY,
        name VARCHAR(50) NOT NULL,
        description VARCHAR(255),
        city VARCHAR(50) NOT NULL,
        address VARCHAR(50) NOT NULL,
        phone_number VARCHAR(50) NOT NULL,
        opening_time TIME NOT NULL,
        closing_time TIME NOT NULL,
        rating FLOAT NOT NULL,
        price VARCHAR(50) NOT NULL,
        cuisine_type INT NOT NULL,
        reservation_duration INT DEFAULT 180,
        image VARBINARY(MAX),

        CONSTRAINT C_price
            CHECK (price IN ('$', '$$', '$$$')),

        CONSTRAINT FK_Restaurants_Cuisines
            FOREIGN KEY (cuisine_type)
            REFERENCES Cuisines(id)
    );
END
GO


IF OBJECT_ID('Tables', 'U') IS NULL
BEGIN
    CREATE TABLE Tables
    (
        id INT IDENTITY(1,1) PRIMARY KEY,
        restaurant_id INT NOT NULL,
        location VARCHAR(50) NOT NULL,
        seats INT NOT NULL,
        total_table_number INT NOT NULL,

        CONSTRAINT FK_Tables_Restaurants
            FOREIGN KEY (restaurant_id)
            REFERENCES Restaurants(id),

        CONSTRAINT C_location
            CHECK (location IN ('window', 'center', 'private', 'garden'))
    );
END
GO


IF OBJECT_ID('MenuItems', 'U') IS NULL
BEGIN
    CREATE TABLE MenuItems
    (
        id INT IDENTITY(1,1) PRIMARY KEY,
        restaurant_id INT NOT NULL,
        food_name VARCHAR(50) NOT NULL,
        description VARCHAR(255),
        price MONEY NOT NULL,
        image VARBINARY(MAX),
        category VARCHAR(50),

        CONSTRAINT FK_MenuItems_Restaurants
            FOREIGN KEY (restaurant_id)
            REFERENCES Restaurants(id),

        CONSTRAINT C_category
            CHECK (category IN ('appetizer', 'main', 'dessert', 'drink'))
    );
END
GO

INSERT INTO Cuisines (cuisine_type)
VALUES 
('Other'),
('Serbian'),
('Mediterranean'),
('International'),
('Italian'),
('Steakhouse'),
('Mexican'),
('Japanese'),
('Chinese');

INSERT INTO Restaurants
(name, description, city, address, phone_number, opening_time, closing_time, rating, price, cuisine_type, reservation_duration, image)
VALUES
('Halo Leskovac', 'Leskovacki roštilj.', 'Beograd', 'Makedonska 22', '+38163221852', '09:00', '03:00', 4.1,	'$', 2,	15,	NULL),
('MOON Sushi & Fusion Food', 'MOON Sushi & Fusion Food je moderan restoran u centru Beograda koji spaja autenticne japanske specijalitete, vrhunski suši i kreativna fusion jela u elegantnom i prijatnom ambijentu.',	'Beograd', 'Makedonska 31',	'+38163344569', '11:00', '23:00', 4.6,	'$$$', 8, 180, NULL),
('Velika Skadarlija', 'Velika Skadarlija je tradicionalni beogradski restoran u srcu Skadarlije, poznat po autentičnoj srpskoj kuhinji, domaćoj atmosferi i starogradskom ambijentu.', 'Beograd', 'Skadarska 40d', '+381640540405', '08:00', '01:00', 4.6, '$$$', 2, 180, NULL),
('Pizza Bar Vračar', 'Picerija sa italijanskom kuhinjom i ponudom pica.', 'Beograd', 'Mutapova 5', '+381640540405', '08:00', '00:00', 4.5, '$', 5, 180, NULL),
('Pizza Bar Novi Beograd', 'Picerija i restoran na Novom Beogradu.', 'Beograd', 'Bulevar Mihajla Pupina 165v', '+381112225467', '08:00', '00:00', 4.6, '$', 5, 180, NULL),
('Picerija Trg', 'Picerija i restoran sa ponudom pica i palačinki na Trgu Republike.', 'Beograd', 'Makedonska 5', '+381641265501', '10:00', '00:30', 4.4, '$', 5, 180, NULL),
('Majstor i Margarita Knez', 'Picerija specijalizovana za italijansku picu.', 'Beograd', 'Vuka Karadžića 12', '+381604808621', '09:00', '00:00', 4.4, '$', 5, 180, NULL),
('Majstor i Margarita Bulevar', 'Picerija sa ponudom tradicionalnih italijanskih pica.', 'Beograd', 'Bulevar kralja Aleksandra 248a', '+381604808625', '09:00', '00:00', 4.5, '$', 5, 180, NULL),
('Picerija Ema', 'Italijanski restoran i pizza bar sa koktelima.', 'Beograd', 'Makenzijeva 45', '+381606003662', '08:00', '00:00', 4.4, '$$', 5, 180, NULL),
('Tortilla Casa Centar', 'Meksički restoran sa tortiljama i drugim meksičkim specijalitetima.', 'Beograd', 'Čika-Ljubina 6', '+381668012656', '09:00', '23:00', 3.9, '$', 7, 180, NULL),
('Tortilla Casa Novi Beograd', 'Meksički restoran sa tortiljama i drugim meksičkim specijalitetima.', 'Beograd', 'Bulevar Zorana Đinđića 48b', '+381668012658', '09:00', '23:00', 4.3, '$', 7, 180, NULL),
('Burrito Madre Terazije', 'Meksički fast food restoran sa buritima i drugim meksičkim jelima.', 'Beograd', 'Terazije 27', '+381113037450', '09:00', '01:00', 4.5, '$', 7, 180, NULL),
('Burrito Madre Bulevar', 'Meksički fast food restoran sa buritima i drugim meksičkim jelima.', 'Beograd', 'Bulevar kralja Aleksandra 182', '+381113037450', '09:00', '01:00', 4.5, '$', 7, 180, NULL),
('Zapata Ciudad', 'Meksički restoran sa tradicionalnim meksičkim jelima.', 'Beograd', 'Vuka Karadžića 14', '+381653809207', '09:00', '00:00', 4.7, '$', 7, 180, NULL),
('Klub književnika', 'Istorijski restoran sa francuskom i internacionalnom kuhinjom.', 'Beograd', 'Francuska 7', '+38163338538', '14:00', '23:00', 4.6, '$$$', 4, 180, NULL),
('Argument', 'Restoran na Mirijevu sa raznovrsnom ponudom jela za ručak i večeru.', 'Beograd', 'Mirijevski bulevar 213', '+381629292892', '08:00', '00:00', 4.6, '$', 4, 180, NULL),
('Koren', 'Restoran sa savremenom gastronomskom ponudom i dobrom svinjetinom.', 'Beograd', 'Bulevar kralja Aleksandra 248', '', '09:00', '23:00', 4.8, '$$', 4, 180, NULL),
('The Pijaca', 'Restoran sa raznovrsnom ponudom hrane i pića.', 'Beograd', 'Vojvode Dovezenskog 2', '+381643503535', '08:00', '00:00', 4.5, '$$', 4, 180, NULL),
('Verona', 'Bar i restoran sa ponudom hrane i pića.', 'Beograd', 'Kraljice Natalije 37', '+381611096885', '08:30', '00:00', 4.7, '$', 2, 180, NULL),
('Republika Pub', 'Pub sa raznovrsnom ponudom burgera, krilaca i piva.', 'Beograd', 'Mileševska 44', '+381604446431', '08:00', '00:00', 4.6, '$', 4, 180, NULL),
('Smash Burgers', 'Fast food restoran specijalizovan za smash burgere.', 'Beograd', 'Takovska 50', '+381605555556', '11:00', '23:00', 4.8, '$', 4, 180, NULL),
('Funk & Soul Pub', 'Gastro pub sa ponudom hrane i pića.', 'Beograd', 'Francuska 6', '+381615006117', '08:00', '00:00', 4.7, '$', 4, 180, NULL),
('Two Guys Smash Burger', 'Fast food restoran specijalizovan za smash burgere.', 'Beograd', 'Požeška 83', '+38169696944', '12:00', '01:00', 4.8, '$', 4, 180, NULL),
('Punch Ramen', 'Ramen restoran sa japanskom kuhinjom.', 'Beograd', 'Maršala Birjuzova 2-4', '+381641438532', '15:00', '22:00', 4.8, '$$', 8, 180, NULL),
('Super Vok Terazije', 'Kineski restoran sa jelima iz voka.', 'Beograd', 'Terazije', '+381112420350', '10:00', '22:00', 4.4, '$', 9, 180, NULL),
('Super Vok Bulevar', 'Kineski restoran sa jelima iz voka.', 'Beograd', 'Bulevar kralja Aleksandra 174', '+381112420350', '10:00', '22:00', 4.4, '$', 9, 180, NULL),
('Bad Ramen', 'Japanski restoran specijalizovan za ramen.', 'Beograd', 'Kneginje Ljubice 8', '+381117349018', '12:00', '22:00', 4.6, '$$', 8, 180, NULL),
('Zavičaj Balkanska', 'Restoran srpske kuhinje.', 'Beograd', 'Gavrila Principa 77', '+38163369670', '09:00', '23:00', 4.5, '$$', 2, 180, NULL),
('Franš Restaurant', 'Restoran sa domaćom i internacionalnom ponudom.', 'Beograd', 'Bulevar oslobođenja 18g', '+381652641944', '09:00', '00:00', 4.7, '$$$', 4, 180, NULL),
('Mezestoran Dvorište', 'Restoran mediteranske kuhinje.', 'Beograd', 'Svetogorska 46', '+381113246515', '09:00', '23:00', 4.7, '$$', 3, 180, NULL),
('Two Kings Restaurant by Hilton', 'Restoran u okviru hotela Hilton sa modernom srpskom i balkanskom kuhinjom.', 'Beograd', 'Kralja Milana 35', '+381648593741', '06:30', '23:00', 4.8, '$$', 4, 180, NULL),
('Mama Restaurant Belgrade', 'Restoran u srcu Beograda.', 'Beograd', 'Kneza Mihaila 54A, Uzun Mirkova 3', '+381113333011', '07:00', '00:00', 4.5, '$$', 4, 180, NULL),
('Comunale Caffe e Cucina', 'Restoran u Beton Hali.', 'Beograd', 'Karađorđeva 2-4, Beton Hala', '+381113037337', '10:00', '01:00', 4.7, '$$', 5, 180, NULL),
('Tri šešira', 'Tradicionalni restoran srpske kuhinje u Skadarliji.', 'Beograd', 'Skadarska 29', '+381603130180', '11:00', '02:00', 4.5, '$$', 2, 180, NULL),
('Steakhouse El Toro', 'Restoran specijalizovan za mesna jela i steakove.', 'Beograd', 'Masarikova 5', '+381691506432', '08:00', '23:00', 4.6, '$$$', 6, 180, NULL),
('Lorenzo & Kakalamba', 'Restoran sa kreativnim enterijerom i internacionalnom ponudom.', 'Beograd', 'Cvijićeva 110', '+381113295351', '12:00', '01:00', 4.6, '$$$', 4, 180, NULL),
('The View Rooftop', 'Rooftop restoran sa pogledom na Beograd.', 'Beograd', 'Internacionalnih brigada 9', '+381668161012', '12:00', '00:00', 4.7, '$$$', 4, 180, NULL),
('Restoran Tri', 'Restoran u Svetogorskoj ulici.', 'Beograd', 'Svetogorska 46', '+381653332543', '11:00', '00:00', 4.6, '$$', 1, 180, NULL),
('Jazz Restaurant', 'Restoran u centru Beograda.', 'Beograd', 'Obilićev venac 17', '+38166214000', '07:00', '01:00', 4.7, '$', 1, 180, NULL),
('Restoran Caruso', 'Restoran na Terazijama.', 'Beograd', 'Terazije 23/8', '+381113248037', '09:00', '00:00', 4.5, '$$', 1, 180, NULL),
('Restoran Enso', 'Restoran sa gastronomskom ponudom više kategorije.', 'Beograd', 'Mitropolita Petra 8', '+38163594924', '15:00', '23:00', 4.7, '$$$', 4, 180, NULL),
('Restoran Mihailo', 'Restoran u centru Beograda.', 'Beograd', 'Obilićev venac 16', '+381114016939', '08:00', '00:00', 4.8, '$$', 1, 180, NULL),
('April Beograd café & restaurant', 'Kafe i restoran u centru Beograda.', 'Beograd', 'Obilićev venac 26', '+381606262620', '08:30', '00:00', 4.6, '$$', 3, 180, NULL),
('Madera', 'Tradicionalni beogradski restoran.', 'Beograd', 'Bulevar kralja Aleksandra 43', '+381113231332', '12:00', '23:00', 4.6, '$$$', 2, 180, NULL),
('Trattoria Pepe', 'Restoran italijanske kuhinje.', 'Beograd', 'Gospodar Jovanova 33', '+381113285295', '09:00', '23:00', 4.6, '$$', 5, 180, NULL),
('Casa Nova', 'Restoran u Gospodar Jovanovoj ulici.', 'Beograd', 'Gospodar Jovanova 42a', '+381113036868', '11:00', '00:00', 4.6, '$$', 4, 180, NULL),
('Durmitor', 'Restoran srpske kuhinje na Novom Beogradu.', 'Beograd', 'Omladinskih brigada 16a', '+381112602330', '08:00', '00:00', 4.7, '$$', 2, 180, NULL);


INSERT INTO MenuItems (restaurant_id, food_name, description, price, image, category)
SELECT
    r.id,
    v.food_name,
    v.description,
    v.price,
    NULL,
    v.category
FROM (VALUES
    ('Halo Leskovac', 'Lepinja sa kajmakom', 'Topla lepinja sa domaćim kajmakom.', 450.00, 'appetizer'),
    ('Halo Leskovac', 'Šopska salata', 'Paradajz, krastavac, paprika, luk i beli sir.', 490.00, 'appetizer'),
    ('Halo Leskovac', 'Domaća proja', 'Proja od kukuruznog brašna sa sirom.', 550.00, 'appetizer'),
    ('Halo Leskovac', 'Mućkalica', 'Dinstano meso sa paprikom, paradajzom i začinima.', 990.00, 'main'),
    ('Halo Leskovac', 'Punjena pljeskavica', 'Pljeskavica punjena sirom sa prilogom.', 1090.00, 'main'),
    ('Halo Leskovac', 'Vešalica na žaru', 'Marinirana svinjska vešalica sa krompirom.', 1190.00, 'main'),
    ('Halo Leskovac', 'Svinjski vrat na žaru', 'Svinjski vrat sa grilovanim povrćem.', 650.00, 'main'),
    ('Halo Leskovac', 'Pileći ražnjići', 'Pileći ražnjići sa povrćem i prilogom.', 690.00, 'main'),
    ('Halo Leskovac', 'Ćevapi sa kajmakom', 'Ćevapi sa lukom, lepinjom i kajmakom.', 750.00, 'main'),
    ('Halo Leskovac', 'Baklava', 'Tradicionalna baklava sa orasima i sirupom.', 290.00, 'dessert'),
    ('Halo Leskovac', 'Orasnice', 'Domaći kolač od oraha.', 320.00, 'dessert'),
    ('Halo Leskovac', 'Pita sa jabukama', 'Topla pita sa jabukama i cimetom.', 350.00, 'dessert'),
    ('Halo Leskovac', 'Kisela voda 0.33l', 'Gazirana mineralna voda.', 290.00, 'drink'),
    ('Halo Leskovac', 'Jogurt 0.25l', 'Hladan jogurt.', 160.00, 'drink'),
    ('Halo Leskovac', 'Espresso', 'Kratka espresso kafa.', 180.00, 'drink'),
    ('Halo Leskovac', 'Coca-Cola 0.33l', 'Gazirano bezalkoholno piće.', 200.00, 'drink'),
    ('MOON Sushi & Fusion Food', 'Edamame', 'Kuvane mlade sojine mahune sa morskom solju.', 1090.00, 'appetizer'),
    ('MOON Sushi & Fusion Food', 'Gyoza', 'Japanske knedle punjene mesom i povrćem.', 1290.00, 'appetizer'),
    ('MOON Sushi & Fusion Food', 'Miso Soup', 'Tradicionalna miso supa sa tofuom i algama.', 790.00, 'appetizer'),
    ('MOON Sushi & Fusion Food', 'Chicken Ramen', 'Ramen sa piletinom, jajetom, povrćem i nudlama.', 2190.00, 'main'),
    ('MOON Sushi & Fusion Food', 'Miso Ramen', 'Ramen u miso bujonu sa povrćem i jajetom.', 2290.00, 'main'),
    ('MOON Sushi & Fusion Food', 'Tempura Udon', 'Udon nudle sa povrćem i tempura dodatkom.', 2490.00, 'main'),
    ('MOON Sushi & Fusion Food', 'Teriyaki Chicken Bowl', 'Piletina u teriyaki sosu sa pirinčem i povrćem.', 2690.00, 'main'),
    ('MOON Sushi & Fusion Food', 'Beef Yakisoba', 'Pržene nudle sa govedinom i povrćem.', 2990.00, 'main'),
    ('MOON Sushi & Fusion Food', 'Vegetable Ramen', 'Ramen sa povrćem i aromatičnim bujonom.', 3290.00, 'main'),
    ('MOON Sushi & Fusion Food', 'Salmon Sushi Set', 'Izbor nigiri i maki sušija sa lososom.', 1590.00, 'main'),
    ('MOON Sushi & Fusion Food', 'Mochi Selection', 'Izbor japanskih mochi kolačića.', 690.00, 'dessert'),
    ('MOON Sushi & Fusion Food', 'Matcha Cheesecake', 'Kremasti cheesecake sa matcha čajem.', 790.00, 'dessert'),
    ('MOON Sushi & Fusion Food', 'Iced Green Tea', 'Hladan zeleni čaj.', 350.00, 'drink'),
    ('MOON Sushi & Fusion Food', 'Ginger Lemonade', 'Limunada sa đumbirom.', 390.00, 'drink'),
    ('MOON Sushi & Fusion Food', 'Green Tea', 'Topao japanski zeleni čaj.', 490.00, 'drink'),
    ('Velika Skadarlija', 'Šopska salata', 'Paradajz, krastavac, paprika, luk i beli sir.', 1290.00, 'appetizer'),
    ('Velika Skadarlija', 'Domaća proja', 'Proja od kukuruznog brašna sa sirom.', 790.00, 'appetizer'),
    ('Velika Skadarlija', 'Leskovački uštipci', 'Pikantni mesni uštipci sa sirom i slaninom.', 2290.00, 'main'),
    ('Velika Skadarlija', 'Pileći file na žaru', 'Pileći file sa grilovanim povrćem i krompirom.', 2490.00, 'main'),
    ('Velika Skadarlija', 'Mućkalica', 'Dinstano meso sa paprikom, paradajzom i začinima.', 2690.00, 'main'),
    ('Velika Skadarlija', 'Punjena pljeskavica', 'Pljeskavica punjena sirom sa prilogom.', 2990.00, 'main'),
    ('Velika Skadarlija', 'Vešalica na žaru', 'Marinirana svinjska vešalica sa krompirom.', 3290.00, 'main'),
    ('Velika Skadarlija', 'Svinjski vrat na žaru', 'Svinjski vrat sa grilovanim povrćem.', 1590.00, 'main'),
    ('Velika Skadarlija', 'Pileći ražnjići', 'Pileći ražnjići sa povrćem i prilogom.', 1690.00, 'main'),
    ('Velika Skadarlija', 'Orasnice', 'Domaći kolač od oraha.', 790.00, 'dessert'),
    ('Velika Skadarlija', 'Pita sa jabukama', 'Topla pita sa jabukama i cimetom.', 550.00, 'dessert'),
    ('Velika Skadarlija', 'Tufahija', 'Pečena jabuka punjena orasima.', 590.00, 'dessert'),
    ('Velika Skadarlija', 'Coca-Cola 0.33l', 'Gazirano bezalkoholno piće.', 390.00, 'drink'),
    ('Velika Skadarlija', 'Sok od pomorandže', 'Voćni sok od pomorandže.', 490.00, 'drink'),
    ('Velika Skadarlija', 'Domaća limunada', 'Sveže ceđena limunada.', 590.00, 'drink'),
    ('Pizza Bar Vračar', 'Minestrone', 'Italijanska supa sa povrćem.', 390.00, 'appetizer'),
    ('Pizza Bar Vračar', 'Arancini', 'Hrskave kuglice od pirinča sa sirom.', 450.00, 'appetizer'),
    ('Pizza Bar Vračar', 'Antipasto Misto', 'Izbor italijanskih sireva, povrća i suhomesnatih proizvoda.', 490.00, 'appetizer'),
    ('Pizza Bar Vračar', 'Bruschetta al Pomodoro', 'Prepečeni hleb, paradajz, beli luk, bosiljak i maslinovo ulje.', 550.00, 'appetizer'),
    ('Pizza Bar Vračar', 'Caprese', 'Paradajz, mozzarella, bosiljak i maslinovo ulje.', 590.00, 'appetizer'),
    ('Pizza Bar Vračar', 'Pizza Capricciosa', 'Paradajz sos, mozzarella, šunka, pečurke i masline.', 1090.00, 'main'),
    ('Pizza Bar Vračar', 'Pizza Vegetariana', 'Paradajz sos, mozzarella i sezonsko povrće.', 1190.00, 'main'),
    ('Pizza Bar Vračar', 'Spaghetti Carbonara', 'Pasta sa pancetom, jajetom, sirom i biberom.', 650.00, 'main'),
    ('Pizza Bar Vračar', 'Lasagne Bolognese', 'Zapečene lazanje sa ragù sosom i bešamelom.', 690.00, 'main'),
    ('Pizza Bar Vračar', 'Penne Arrabbiata', 'Penne u pikantnom paradajz sosu.', 750.00, 'main'),
    ('Pizza Bar Vračar', 'Tagliatelle al Funghi', 'Tagliatelle sa pečurkama u kremastom sosu.', 790.00, 'main'),
    ('Pizza Bar Vračar', 'Tiramisu', 'Klasični italijanski desert sa mascarpone kremom i kafom.', 350.00, 'dessert'),
    ('Pizza Bar Vračar', 'Panna Cotta', 'Panna cotta sa voćnim prelivom.', 390.00, 'dessert'),
    ('Pizza Bar Vračar', 'Cannoli', 'Hrskave rolnice punjene kremom od ricotte.', 450.00, 'dessert'),
    ('Pizza Bar Vračar', 'Mineralna voda 0.33l', 'Gazirana mineralna voda.', 180.00, 'drink'),
    ('Pizza Bar Vračar', 'Espresso', 'Klasični italijanski espresso.', 200.00, 'drink'),
    ('Pizza Bar Vračar', 'Ledeni čaj', 'Hladan čaj sa limunom.', 220.00, 'drink'),
    ('Pizza Bar Novi Beograd', 'Arancini', 'Hrskave kuglice od pirinča sa sirom.', 550.00, 'appetizer'),
    ('Pizza Bar Novi Beograd', 'Antipasto Misto', 'Izbor italijanskih sireva, povrća i suhomesnatih proizvoda.', 590.00, 'appetizer'),
    ('Pizza Bar Novi Beograd', 'Bruschetta al Pomodoro', 'Prepečeni hleb, paradajz, beli luk, bosiljak i maslinovo ulje.', 350.00, 'appetizer'),
    ('Pizza Bar Novi Beograd', 'Spaghetti Carbonara', 'Pasta sa pancetom, jajetom, sirom i biberom.', 1190.00, 'main'),
    ('Pizza Bar Novi Beograd', 'Lasagne Bolognese', 'Zapečene lazanje sa ragù sosom i bešamelom.', 650.00, 'main'),
    ('Pizza Bar Novi Beograd', 'Penne Arrabbiata', 'Penne u pikantnom paradajz sosu.', 690.00, 'main'),
    ('Pizza Bar Novi Beograd', 'Tagliatelle al Funghi', 'Tagliatelle sa pečurkama u kremastom sosu.', 750.00, 'main'),
    ('Pizza Bar Novi Beograd', 'Pizza Margherita', 'Paradajz sos, mozzarella i bosiljak.', 790.00, 'main'),
    ('Pizza Bar Novi Beograd', 'Panna Cotta', 'Panna cotta sa voćnim prelivom.', 390.00, 'dessert'),
    ('Pizza Bar Novi Beograd', 'Cannoli', 'Hrskave rolnice punjene kremom od ricotte.', 450.00, 'dessert'),
    ('Pizza Bar Novi Beograd', 'Mineralna voda 0.33l', 'Gazirana mineralna voda.', 200.00, 'drink'),
    ('Pizza Bar Novi Beograd', 'Espresso', 'Klasični italijanski espresso.', 220.00, 'drink'),
    ('Pizza Bar Novi Beograd', 'Ledeni čaj', 'Hladan čaj sa limunom.', 250.00, 'drink'),
    ('Picerija Trg', 'Antipasto Misto', 'Izbor italijanskih sireva, povrća i suhomesnatih proizvoda.', 450.00, 'appetizer'),
    ('Picerija Trg', 'Bruschetta al Pomodoro', 'Prepečeni hleb, paradajz, beli luk, bosiljak i maslinovo ulje.', 490.00, 'appetizer'),
    ('Picerija Trg', 'Caprese', 'Paradajz, mozzarella, bosiljak i maslinovo ulje.', 550.00, 'appetizer'),
    ('Picerija Trg', 'Pizza Prosciutto e Funghi', 'Paradajz sos, mozzarella, šunka i pečurke.', 750.00, 'main'),
    ('Picerija Trg', 'Pizza Capricciosa', 'Paradajz sos, mozzarella, šunka, pečurke i masline.', 790.00, 'main'),
    ('Picerija Trg', 'Pizza Vegetariana', 'Paradajz sos, mozzarella i sezonsko povrće.', 850.00, 'main'),
    ('Picerija Trg', 'Spaghetti Carbonara', 'Pasta sa pancetom, jajetom, sirom i biberom.', 890.00, 'main'),
    ('Picerija Trg', 'Lasagne Bolognese', 'Zapečene lazanje sa ragù sosom i bešamelom.', 950.00, 'main'),
    ('Picerija Trg', 'Penne Arrabbiata', 'Penne u pikantnom paradajz sosu.', 990.00, 'main'),
    ('Picerija Trg', 'Panna Cotta', 'Panna cotta sa voćnim prelivom.', 450.00, 'dessert'),
    ('Picerija Trg', 'Cannoli', 'Hrskave rolnice punjene kremom od ricotte.', 290.00, 'dessert'),
    ('Picerija Trg', 'Gelato', 'Dve kugle italijanskog sladoleda.', 320.00, 'dessert'),
    ('Picerija Trg', 'Limonata', 'Italijanska limunada sa svežim limunom.', 200.00, 'drink'),
    ('Picerija Trg', 'Mineralna voda 0.33l', 'Gazirana mineralna voda.', 220.00, 'drink'),
    ('Picerija Trg', 'Espresso', 'Klasični italijanski espresso.', 250.00, 'drink'),
    ('Picerija Trg', 'Ledeni čaj', 'Hladan čaj sa limunom.', 290.00, 'drink'),
    ('Majstor i Margarita Knez', 'Antipasto Misto', 'Izbor italijanskih sireva, povrća i suhomesnatih proizvoda.', 450.00, 'appetizer'),
    ('Majstor i Margarita Knez', 'Bruschetta al Pomodoro', 'Prepečeni hleb, paradajz, beli luk, bosiljak i maslinovo ulje.', 490.00, 'appetizer'),
    ('Majstor i Margarita Knez', 'Caprese', 'Paradajz, mozzarella, bosiljak i maslinovo ulje.', 550.00, 'appetizer'),
    ('Majstor i Margarita Knez', 'Focaccia', 'Pečena focaccia sa ruzmarinom i maslinovim uljem.', 590.00, 'appetizer'),
    ('Majstor i Margarita Knez', 'Minestrone', 'Italijanska supa sa povrćem.', 350.00, 'appetizer'),
    ('Majstor i Margarita Knez', 'Penne Arrabbiata', 'Penne u pikantnom paradajz sosu.', 990.00, 'main'),
    ('Majstor i Margarita Knez', 'Tagliatelle al Funghi', 'Tagliatelle sa pečurkama u kremastom sosu.', 1090.00, 'main'),
    ('Majstor i Margarita Knez', 'Pizza Margherita', 'Paradajz sos, mozzarella i bosiljak.', 1190.00, 'main'),
    ('Majstor i Margarita Knez', 'Pizza Diavola', 'Paradajz sos, mozzarella i pikantna salama.', 650.00, 'main'),
    ('Majstor i Margarita Knez', 'Pizza Quattro Formaggi', 'Pizza sa četiri vrste sira.', 690.00, 'main'),
    ('Majstor i Margarita Knez', 'Pizza Prosciutto e Funghi', 'Paradajz sos, mozzarella, šunka i pečurke.', 750.00, 'main'),
    ('Majstor i Margarita Knez', 'Cannoli', 'Hrskave rolnice punjene kremom od ricotte.', 450.00, 'dessert'),
    ('Majstor i Margarita Knez', 'Gelato', 'Dve kugle italijanskog sladoleda.', 290.00, 'dessert'),
    ('Majstor i Margarita Knez', 'Affogato', 'Sladoled od vanile preliven espressom.', 320.00, 'dessert'),
    ('Majstor i Margarita Knez', 'Sok od pomorandže', 'Voćni sok od pomorandže.', 290.00, 'drink'),
    ('Majstor i Margarita Knez', 'Limonata', 'Italijanska limunada sa svežim limunom.', 160.00, 'drink'),
    ('Majstor i Margarita Knez', 'Mineralna voda 0.33l', 'Gazirana mineralna voda.', 180.00, 'drink'),
    ('Majstor i Margarita Bulevar', 'Caprese', 'Paradajz, mozzarella, bosiljak i maslinovo ulje.', 350.00, 'appetizer'),
    ('Majstor i Margarita Bulevar', 'Focaccia', 'Pečena focaccia sa ruzmarinom i maslinovim uljem.', 390.00, 'appetizer'),
    ('Majstor i Margarita Bulevar', 'Minestrone', 'Italijanska supa sa povrćem.', 450.00, 'appetizer'),
    ('Majstor i Margarita Bulevar', 'Arancini', 'Hrskave kuglice od pirinča sa sirom.', 490.00, 'appetizer'),
    ('Majstor i Margarita Bulevar', 'Pizza Margherita', 'Paradajz sos, mozzarella i bosiljak.', 1190.00, 'main'),
    ('Majstor i Margarita Bulevar', 'Pizza Diavola', 'Paradajz sos, mozzarella i pikantna salama.', 650.00, 'main'),
    ('Majstor i Margarita Bulevar', 'Pizza Quattro Formaggi', 'Pizza sa četiri vrste sira.', 690.00, 'main'),
    ('Majstor i Margarita Bulevar', 'Pizza Prosciutto e Funghi', 'Paradajz sos, mozzarella, šunka i pečurke.', 750.00, 'main'),
    ('Majstor i Margarita Bulevar', 'Pizza Capricciosa', 'Paradajz sos, mozzarella, šunka, pečurke i masline.', 790.00, 'main'),
    ('Majstor i Margarita Bulevar', 'Pizza Vegetariana', 'Paradajz sos, mozzarella i sezonsko povrće.', 850.00, 'main'),
    ('Majstor i Margarita Bulevar', 'Cannoli', 'Hrskave rolnice punjene kremom od ricotte.', 290.00, 'dessert'),
    ('Majstor i Margarita Bulevar', 'Gelato', 'Dve kugle italijanskog sladoleda.', 320.00, 'dessert'),
    ('Majstor i Margarita Bulevar', 'Affogato', 'Sladoled od vanile preliven espressom.', 350.00, 'dessert'),
    ('Majstor i Margarita Bulevar', 'Sok od pomorandže', 'Voćni sok od pomorandže.', 250.00, 'drink'),
    ('Majstor i Margarita Bulevar', 'Limonata', 'Italijanska limunada sa svežim limunom.', 290.00, 'drink'),
    ('Majstor i Margarita Bulevar', 'Mineralna voda 0.33l', 'Gazirana mineralna voda.', 160.00, 'drink'),
    ('Majstor i Margarita Bulevar', 'Espresso', 'Klasični italijanski espresso.', 180.00, 'drink'),
    ('Picerija Ema', 'Bruschetta al Pomodoro', 'Prepečeni hleb, paradajz, beli luk, bosiljak i maslinovo ulje.', 690.00, 'appetizer'),
    ('Picerija Ema', 'Caprese', 'Paradajz, mozzarella, bosiljak i maslinovo ulje.', 790.00, 'appetizer'),
    ('Picerija Ema', 'Focaccia', 'Pečena focaccia sa ruzmarinom i maslinovim uljem.', 890.00, 'appetizer'),
    ('Picerija Ema', 'Pizza Diavola', 'Paradajz sos, mozzarella i pikantna salama.', 1290.00, 'main'),
    ('Picerija Ema', 'Pizza Quattro Formaggi', 'Pizza sa četiri vrste sira.', 1390.00, 'main'),
    ('Picerija Ema', 'Pizza Prosciutto e Funghi', 'Paradajz sos, mozzarella, šunka i pečurke.', 1490.00, 'main'),
    ('Picerija Ema', 'Pizza Capricciosa', 'Paradajz sos, mozzarella, šunka, pečurke i masline.', 1590.00, 'main'),
    ('Picerija Ema', 'Pizza Vegetariana', 'Paradajz sos, mozzarella i sezonsko povrće.', 1690.00, 'main'),
    ('Picerija Ema', 'Panna Cotta', 'Panna cotta sa voćnim prelivom.', 590.00, 'dessert'),
    ('Picerija Ema', 'Cannoli', 'Hrskave rolnice punjene kremom od ricotte.', 390.00, 'dessert'),
    ('Picerija Ema', 'Cappuccino', 'Espresso sa mlečnom penom.', 390.00, 'drink'),
    ('Picerija Ema', 'Sok od pomorandže', 'Voćni sok od pomorandže.', 220.00, 'drink'),
    ('Picerija Ema', 'Limonata', 'Italijanska limunada sa svežim limunom.', 250.00, 'drink'),
    ('Tortilla Casa Centar', 'Quesadilla Starter', 'Mala quesadilla sa sirom i salsom.', 550.00, 'appetizer'),
    ('Tortilla Casa Centar', 'Elote', 'Kukuruz sa kremastim prelivom, sirom i začinima.', 590.00, 'appetizer'),
    ('Tortilla Casa Centar', 'Loaded Nachos', 'Nachos sa sirom, pasuljem, salsom i jalapeñom.', 350.00, 'appetizer'),
    ('Tortilla Casa Centar', 'Chili con Carne', 'Začinjeno goveđe meso sa pasuljem i paradajzom.', 650.00, 'main'),
    ('Tortilla Casa Centar', 'Veggie Quesadilla', 'Quesadilla sa povrćem i sirom.', 690.00, 'main'),
    ('Tortilla Casa Centar', 'Chicken Burrito', 'Burrito sa piletinom, pirinčem, pasuljem, povrćem i salsom.', 750.00, 'main'),
    ('Tortilla Casa Centar', 'Beef Burrito', 'Burrito sa govedinom, pirinčem, pasuljem i salsom.', 790.00, 'main'),
    ('Tortilla Casa Centar', 'Tacos al Pastor', 'Tri tortilje sa začinjenim mesom, lukom i salsom.', 850.00, 'main'),
    ('Tortilla Casa Centar', 'Veggie Burrito', 'Burrito sa povrćem, pirinčem, pasuljem i guacamoleom.', 890.00, 'main'),
    ('Tortilla Casa Centar', 'Cinnamon Nachos', 'Slatki tortilja čips sa cimetom i šećerom.', 350.00, 'dessert'),
    ('Tortilla Casa Centar', 'Churros', 'Prženo testo sa cimetom i čokoladnim sosom.', 390.00, 'dessert'),
    ('Tortilla Casa Centar', 'Tres Leches', 'Sočan mlečni kolač sa laganom kremom.', 450.00, 'dessert'),
    ('Tortilla Casa Centar', 'Horchata', 'Hladan napitak od pirinča i cimeta.', 290.00, 'drink'),
    ('Tortilla Casa Centar', 'Cola 0.33l', 'Gazirano bezalkoholno piće.', 160.00, 'drink'),
    ('Tortilla Casa Centar', 'Mineralna voda 0.33l', 'Gazirana mineralna voda.', 180.00, 'drink'),
    ('Tortilla Casa Centar', 'Mango Agua Fresca', 'Osvežavajući napitak od manga.', 200.00, 'drink'),
    ('Tortilla Casa Novi Beograd', 'Mini Tacos', 'Tri mala tacos-a sa povrćem i salsom.', 550.00, 'appetizer'),
    ('Tortilla Casa Novi Beograd', 'Nachos & Salsa', 'Tortilja čips sa paradajz salsom.', 590.00, 'appetizer'),
    ('Tortilla Casa Novi Beograd', 'Guacamole & Chips', 'Svež guacamole sa tortilja čipsom.', 350.00, 'appetizer'),
    ('Tortilla Casa Novi Beograd', 'Chili con Carne', 'Začinjeno goveđe meso sa pasuljem i paradajzom.', 690.00, 'main'),
    ('Tortilla Casa Novi Beograd', 'Veggie Quesadilla', 'Quesadilla sa povrćem i sirom.', 750.00, 'main'),
    ('Tortilla Casa Novi Beograd', 'Chicken Burrito', 'Burrito sa piletinom, pirinčem, pasuljem, povrćem i salsom.', 790.00, 'main'),
    ('Tortilla Casa Novi Beograd', 'Beef Burrito', 'Burrito sa govedinom, pirinčem, pasuljem i salsom.', 850.00, 'main'),
    ('Tortilla Casa Novi Beograd', 'Tacos al Pastor', 'Tri tortilje sa začinjenim mesom, lukom i salsom.', 890.00, 'main'),
    ('Tortilla Casa Novi Beograd', 'Veggie Burrito', 'Burrito sa povrćem, pirinčem, pasuljem i guacamoleom.', 950.00, 'main'),
    ('Tortilla Casa Novi Beograd', 'Chocolate Quesadilla', 'Slatka tortilja sa čokoladnim punjenjem.', 390.00, 'dessert'),
    ('Tortilla Casa Novi Beograd', 'Cinnamon Nachos', 'Slatki tortilja čips sa cimetom i šećerom.', 450.00, 'dessert'),
    ('Tortilla Casa Novi Beograd', 'Churros', 'Prženo testo sa cimetom i čokoladnim sosom.', 290.00, 'dessert'),
    ('Tortilla Casa Novi Beograd', 'Iced Tea', 'Hladan čaj sa citrusima.', 160.00, 'drink'),
    ('Tortilla Casa Novi Beograd', 'Lime Agua Fresca', 'Osvežavajući napitak od limete.', 180.00, 'drink'),
    ('Tortilla Casa Novi Beograd', 'Horchata', 'Hladan napitak od pirinča i cimeta.', 200.00, 'drink'),
    ('Burrito Madre Terazije', 'Mini Tacos', 'Tri mala tacos-a sa povrćem i salsom.', 590.00, 'appetizer'),
    ('Burrito Madre Terazije', 'Nachos & Salsa', 'Tortilja čips sa paradajz salsom.', 350.00, 'appetizer'),
    ('Burrito Madre Terazije', 'Guacamole & Chips', 'Svež guacamole sa tortilja čipsom.', 390.00, 'appetizer'),
    ('Burrito Madre Terazije', 'Veggie Quesadilla', 'Quesadilla sa povrćem i sirom.', 1090.00, 'main'),
    ('Burrito Madre Terazije', 'Chicken Burrito', 'Burrito sa piletinom, pirinčem, pasuljem, povrćem i salsom.', 1190.00, 'main'),
    ('Burrito Madre Terazije', 'Beef Burrito', 'Burrito sa govedinom, pirinčem, pasuljem i salsom.', 650.00, 'main'),
    ('Burrito Madre Terazije', 'Tacos al Pastor', 'Tri tortilje sa začinjenim mesom, lukom i salsom.', 690.00, 'main'),
    ('Burrito Madre Terazije', 'Veggie Burrito', 'Burrito sa povrćem, pirinčem, pasuljem i guacamoleom.', 750.00, 'main'),
    ('Burrito Madre Terazije', 'Cinnamon Nachos', 'Slatki tortilja čips sa cimetom i šećerom.', 350.00, 'dessert'),
    ('Burrito Madre Terazije', 'Churros', 'Prženo testo sa cimetom i čokoladnim sosom.', 390.00, 'dessert'),
    ('Burrito Madre Terazije', 'Mineralna voda 0.33l', 'Gazirana mineralna voda.', 220.00, 'drink'),
    ('Burrito Madre Terazije', 'Mango Agua Fresca', 'Osvežavajući napitak od manga.', 250.00, 'drink'),
    ('Burrito Madre Terazije', 'Iced Tea', 'Hladan čaj sa citrusima.', 290.00, 'drink'),
    ('Burrito Madre Bulevar', 'Nachos & Salsa', 'Tortilja čips sa paradajz salsom.', 550.00, 'appetizer'),
    ('Burrito Madre Bulevar', 'Guacamole & Chips', 'Svež guacamole sa tortilja čipsom.', 590.00, 'appetizer'),
    ('Burrito Madre Bulevar', 'Quesadilla Starter', 'Mala quesadilla sa sirom i salsom.', 350.00, 'appetizer'),
    ('Burrito Madre Bulevar', 'Beef Burrito', 'Burrito sa govedinom, pirinčem, pasuljem i salsom.', 690.00, 'main'),
    ('Burrito Madre Bulevar', 'Tacos al Pastor', 'Tri tortilje sa začinjenim mesom, lukom i salsom.', 750.00, 'main'),
    ('Burrito Madre Bulevar', 'Veggie Burrito', 'Burrito sa povrćem, pirinčem, pasuljem i guacamoleom.', 790.00, 'main'),
    ('Burrito Madre Bulevar', 'Chicken Quesadilla', 'Tortilja sa piletinom, sirom i salsom.', 850.00, 'main'),
    ('Burrito Madre Bulevar', 'Burrito Bowl', 'Pirinčana činija sa mesom, pasuljem, povrćem i salsom.', 890.00, 'main'),
    ('Burrito Madre Bulevar', 'Beef Quesadilla', 'Tortilja sa govedinom, sirom i salsom.', 950.00, 'main'),
    ('Burrito Madre Bulevar', 'Churros', 'Prženo testo sa cimetom i čokoladnim sosom.', 350.00, 'dessert'),
    ('Burrito Madre Bulevar', 'Tres Leches', 'Sočan mlečni kolač sa laganom kremom.', 390.00, 'dessert'),
    ('Burrito Madre Bulevar', 'Caramel Flan', 'Kremasti flan sa karamelom.', 450.00, 'dessert'),
    ('Burrito Madre Bulevar', 'Cola 0.33l', 'Gazirano bezalkoholno piće.', 220.00, 'drink'),
    ('Burrito Madre Bulevar', 'Mineralna voda 0.33l', 'Gazirana mineralna voda.', 250.00, 'drink'),
    ('Burrito Madre Bulevar', 'Mango Agua Fresca', 'Osvežavajući napitak od manga.', 290.00, 'drink'),
    ('Zapata Ciudad', 'Quesadilla Starter', 'Mala quesadilla sa sirom i salsom.', 390.00, 'appetizer'),
    ('Zapata Ciudad', 'Elote', 'Kukuruz sa kremastim prelivom, sirom i začinima.', 450.00, 'appetizer'),
    ('Zapata Ciudad', 'Loaded Nachos', 'Nachos sa sirom, pasuljem, salsom i jalapeñom.', 490.00, 'appetizer'),
    ('Zapata Ciudad', 'Tacos al Pastor', 'Tri tortilje sa začinjenim mesom, lukom i salsom.', 1190.00, 'main'),
    ('Zapata Ciudad', 'Veggie Burrito', 'Burrito sa povrćem, pirinčem, pasuljem i guacamoleom.', 650.00, 'main'),
    ('Zapata Ciudad', 'Chicken Quesadilla', 'Tortilja sa piletinom, sirom i salsom.', 690.00, 'main'),
    ('Zapata Ciudad', 'Burrito Bowl', 'Pirinčana činija sa mesom, pasuljem, povrćem i salsom.', 750.00, 'main'),
    ('Zapata Ciudad', 'Beef Quesadilla', 'Tortilja sa govedinom, sirom i salsom.', 790.00, 'main'),
    ('Zapata Ciudad', 'Chicken Tacos', 'Tri tacos-a sa piletinom, povrćem i salsom.', 850.00, 'main'),
    ('Zapata Ciudad', 'Churros', 'Prženo testo sa cimetom i čokoladnim sosom.', 290.00, 'dessert'),
    ('Zapata Ciudad', 'Tres Leches', 'Sočan mlečni kolač sa laganom kremom.', 320.00, 'dessert'),
    ('Zapata Ciudad', 'Caramel Flan', 'Kremasti flan sa karamelom.', 350.00, 'dessert'),
    ('Zapata Ciudad', 'Mineralna voda 0.33l', 'Gazirana mineralna voda.', 200.00, 'drink'),
    ('Zapata Ciudad', 'Mango Agua Fresca', 'Osvežavajući napitak od manga.', 220.00, 'drink'),
    ('Zapata Ciudad', 'Iced Tea', 'Hladan čaj sa citrusima.', 250.00, 'drink'),
    ('Zapata Ciudad', 'Lime Agua Fresca', 'Osvežavajući napitak od limete.', 290.00, 'drink'),
    ('Klub književnika', 'Chicken Wings', 'Hrskava pileća krilca sa sosom.', 1090.00, 'appetizer'),
    ('Klub književnika', 'Onion Rings', 'Hrskavi kolutovi luka sa dip sosom.', 1290.00, 'appetizer'),
    ('Klub književnika', 'Grilled Chicken', 'Pileći file sa grilovanim povrćem i krompirom.', 1890.00, 'main'),
    ('Klub književnika', 'Penne Chicken', 'Penne pasta sa piletinom u kremastom sosu.', 1990.00, 'main'),
    ('Klub književnika', 'BBQ Ribs', 'Sporo pečena rebra sa BBQ sosom i krompirom.', 2190.00, 'main'),
    ('Klub književnika', 'Fish & Chips', 'Pohovana riba sa pomfritom i tartar sosom.', 2290.00, 'main'),
    ('Klub književnika', 'Chicken Wrap', 'Tortilja sa piletinom, povrćem i sosom.', 2490.00, 'main'),
    ('Klub književnika', 'Vegetable Pasta', 'Pasta sa sezonskim povrćem i paradajz sosom.', 2690.00, 'main'),
    ('Klub književnika', 'Classic Burger', 'Goveđi burger sa sirom, povrćem i pomfritom.', 2990.00, 'main'),
    ('Klub književnika', 'Brownie', 'Čokoladni brownie sa prelivom.', 590.00, 'dessert'),
    ('Klub književnika', 'Chocolate Cake', 'Čokoladni kolač sa kremastim filom.', 650.00, 'dessert'),
    ('Klub književnika', 'Cheesecake', 'Kremasti cheesecake sa voćnim prelivom.', 690.00, 'dessert'),
    ('Klub književnika', 'Iced Tea', 'Hladan čaj sa limunom.', 350.00, 'drink'),
    ('Klub književnika', 'Orange Juice', 'Voćni sok od pomorandže.', 390.00, 'drink'),
    ('Klub književnika', 'Fresh Lemonade', 'Sveže ceđena limunada.', 490.00, 'drink'),
    ('Argument', 'Bruschetta', 'Prepečeni hleb sa paradajzom, bosiljkom i maslinovim uljem.', 450.00, 'appetizer'),
    ('Argument', 'Chicken Wings', 'Hrskava pileća krilca sa sosom.', 490.00, 'appetizer'),
    ('Argument', 'Onion Rings', 'Hrskavi kolutovi luka sa dip sosom.', 550.00, 'appetizer'),
    ('Argument', 'Caesar Salad', 'Rimska salata, parmezan, krutoni i Caesar dresing.', 590.00, 'appetizer'),
    ('Argument', 'Fish & Chips', 'Pohovana riba sa pomfritom i tartar sosom.', 990.00, 'main'),
    ('Argument', 'Chicken Wrap', 'Tortilja sa piletinom, povrćem i sosom.', 1090.00, 'main'),
    ('Argument', 'Vegetable Pasta', 'Pasta sa sezonskim povrćem i paradajz sosom.', 1190.00, 'main'),
    ('Argument', 'Classic Burger', 'Goveđi burger sa sirom, povrćem i pomfritom.', 650.00, 'main'),
    ('Argument', 'Chicken Burger', 'Pileći burger sa salatom, sosom i pomfritom.', 690.00, 'main'),
    ('Argument', 'Double Smash Burger', 'Dupla smash pljeskavica sa sirom i sosom.', 750.00, 'main'),
    ('Argument', 'Club Sandwich', 'Sendvič sa piletinom, slaninom, salatom i pomfritom.', 790.00, 'main'),
    ('Argument', 'Chocolate Cake', 'Čokoladni kolač sa kremastim filom.', 450.00, 'dessert'),
    ('Argument', 'Cheesecake', 'Kremasti cheesecake sa voćnim prelivom.', 290.00, 'dessert'),
    ('Argument', 'Pancakes', 'Palačinke sa kremom i sezonskim voćem.', 320.00, 'dessert'),
    ('Argument', 'Orange Juice', 'Voćni sok od pomorandže.', 220.00, 'drink'),
    ('Argument', 'Fresh Lemonade', 'Sveže ceđena limunada.', 250.00, 'drink'),
    ('Argument', 'Cola 0.33l', 'Gazirano bezalkoholno piće.', 290.00, 'drink'),
    ('Koren', 'Caesar Salad', 'Rimska salata, parmezan, krutoni i Caesar dresing.', 890.00, 'appetizer'),
    ('Koren', 'Mozzarella Sticks', 'Pohovani mozzarella štapići sa dip sosom.', 550.00, 'appetizer'),
    ('Koren', 'Nachos', 'Tortilja čips sa sirom i salsom.', 590.00, 'appetizer'),
    ('Koren', 'Bruschetta', 'Prepečeni hleb sa paradajzom, bosiljkom i maslinovim uljem.', 650.00, 'appetizer'),
    ('Koren', 'Chicken Wings', 'Hrskava pileća krilca sa sosom.', 690.00, 'appetizer'),
    ('Koren', 'Classic Burger', 'Goveđi burger sa sirom, povrćem i pomfritom.', 990.00, 'main'),
    ('Koren', 'Chicken Burger', 'Pileći burger sa salatom, sosom i pomfritom.', 1090.00, 'main'),
    ('Koren', 'Double Smash Burger', 'Dupla smash pljeskavica sa sirom i sosom.', 1190.00, 'main'),
    ('Koren', 'Club Sandwich', 'Sendvič sa piletinom, slaninom, salatom i pomfritom.', 1290.00, 'main'),
    ('Koren', 'Grilled Chicken', 'Pileći file sa grilovanim povrćem i krompirom.', 1390.00, 'main'),
    ('Koren', 'Penne Chicken', 'Penne pasta sa piletinom u kremastom sosu.', 1490.00, 'main'),
    ('Koren', 'Apple Pie', 'Pita sa jabukama i cimetom.', 520.00, 'dessert'),
    ('Koren', 'Brownie', 'Čokoladni brownie sa prelivom.', 590.00, 'dessert'),
    ('Koren', 'Chocolate Cake', 'Čokoladni kolač sa kremastim filom.', 390.00, 'dessert'),
    ('Koren', 'Orange Juice', 'Voćni sok od pomorandže.', 390.00, 'drink'),
    ('Koren', 'Fresh Lemonade', 'Sveže ceđena limunada.', 220.00, 'drink'),
    ('Koren', 'Cola 0.33l', 'Gazirano bezalkoholno piće.', 250.00, 'drink'),
    ('The Pijaca', 'Nachos', 'Tortilja čips sa sirom i salsom.', 550.00, 'appetizer'),
    ('The Pijaca', 'Bruschetta', 'Prepečeni hleb sa paradajzom, bosiljkom i maslinovim uljem.', 590.00, 'appetizer'),
    ('The Pijaca', 'Chicken Wings', 'Hrskava pileća krilca sa sosom.', 650.00, 'appetizer'),
    ('The Pijaca', 'Onion Rings', 'Hrskavi kolutovi luka sa dip sosom.', 690.00, 'appetizer'),
    ('The Pijaca', 'Caesar Salad', 'Rimska salata, parmezan, krutoni i Caesar dresing.', 790.00, 'appetizer'),
    ('The Pijaca', 'Fish & Chips', 'Pohovana riba sa pomfritom i tartar sosom.', 1390.00, 'main'),
    ('The Pijaca', 'Chicken Wrap', 'Tortilja sa piletinom, povrćem i sosom.', 1490.00, 'main'),
    ('The Pijaca', 'Vegetable Pasta', 'Pasta sa sezonskim povrćem i paradajz sosom.', 1590.00, 'main'),
    ('The Pijaca', 'Classic Burger', 'Goveđi burger sa sirom, povrćem i pomfritom.', 1690.00, 'main'),
    ('The Pijaca', 'Chicken Burger', 'Pileći burger sa salatom, sosom i pomfritom.', 1790.00, 'main'),
    ('The Pijaca', 'Double Smash Burger', 'Dupla smash pljeskavica sa sirom i sosom.', 950.00, 'main'),
    ('The Pijaca', 'Apple Pie', 'Pita sa jabukama i cimetom.', 450.00, 'dessert'),
    ('The Pijaca', 'Brownie', 'Čokoladni brownie sa prelivom.', 490.00, 'dessert'),
    ('The Pijaca', 'Chocolate Cake', 'Čokoladni kolač sa kremastim filom.', 520.00, 'dessert'),
    ('The Pijaca', 'Espresso', 'Espresso kafa.', 320.00, 'drink'),
    ('The Pijaca', 'Mineralna voda 0.33l', 'Mineralna voda.', 350.00, 'drink'),
    ('The Pijaca', 'Iced Tea', 'Hladan čaj sa limunom.', 390.00, 'drink'),
    ('Verona', 'Pečena paprika sa belim lukom', 'Pečena paprika sa uljem, peršunom i belim lukom.', 490.00, 'appetizer'),
    ('Verona', 'Sir sa kajmakom', 'Izbor domaćeg sira i kajmaka.', 550.00, 'appetizer'),
    ('Verona', 'Lepinja sa kajmakom', 'Topla lepinja sa domaćim kajmakom.', 590.00, 'appetizer'),
    ('Verona', 'Mućkalica', 'Dinstano meso sa paprikom, paradajzom i začinima.', 790.00, 'main'),
    ('Verona', 'Punjena pljeskavica', 'Pljeskavica punjena sirom sa prilogom.', 850.00, 'main'),
    ('Verona', 'Vešalica na žaru', 'Marinirana svinjska vešalica sa krompirom.', 890.00, 'main'),
    ('Verona', 'Svinjski vrat na žaru', 'Svinjski vrat sa grilovanim povrćem.', 950.00, 'main'),
    ('Verona', 'Pileći ražnjići', 'Pileći ražnjići sa povrćem i prilogom.', 990.00, 'main'),
    ('Verona', 'Ćevapi sa kajmakom', 'Ćevapi sa lukom, lepinjom i kajmakom.', 1090.00, 'main'),
    ('Verona', 'Pita sa jabukama', 'Topla pita sa jabukama i cimetom.', 320.00, 'dessert'),
    ('Verona', 'Tufahija', 'Pečena jabuka punjena orasima.', 350.00, 'dessert'),
    ('Verona', 'Palačinke sa kremom', 'Domaće palačinke sa kremom i mlevenim keksom.', 390.00, 'dessert'),
    ('Verona', 'Jogurt 0.25l', 'Hladan jogurt.', 250.00, 'drink'),
    ('Verona', 'Espresso', 'Kratka espresso kafa.', 290.00, 'drink'),
    ('Verona', 'Coca-Cola 0.33l', 'Gazirano bezalkoholno piće.', 160.00, 'drink'),
    ('Verona', 'Sok od pomorandže', 'Voćni sok od pomorandže.', 180.00, 'drink'),
    ('Republika Pub', 'Onion Rings', 'Hrskavi kolutovi luka sa dip sosom.', 590.00, 'appetizer'),
    ('Republika Pub', 'Caesar Salad', 'Rimska salata, parmezan, krutoni i Caesar dresing.', 350.00, 'appetizer'),
    ('Republika Pub', 'Mozzarella Sticks', 'Pohovani mozzarella štapići sa dip sosom.', 390.00, 'appetizer'),
    ('Republika Pub', 'Nachos', 'Tortilja čips sa sirom i salsom.', 450.00, 'appetizer'),
    ('Republika Pub', 'Bruschetta', 'Prepečeni hleb sa paradajzom, bosiljkom i maslinovim uljem.', 490.00, 'appetizer'),
    ('Republika Pub', 'Classic Burger', 'Goveđi burger sa sirom, povrćem i pomfritom.', 990.00, 'main'),
    ('Republika Pub', 'Chicken Burger', 'Pileći burger sa salatom, sosom i pomfritom.', 1090.00, 'main'),
    ('Republika Pub', 'Double Smash Burger', 'Dupla smash pljeskavica sa sirom i sosom.', 1190.00, 'main'),
    ('Republika Pub', 'Club Sandwich', 'Sendvič sa piletinom, slaninom, salatom i pomfritom.', 650.00, 'main'),
    ('Republika Pub', 'Grilled Chicken', 'Pileći file sa grilovanim povrćem i krompirom.', 690.00, 'main'),
    ('Republika Pub', 'Penne Chicken', 'Penne pasta sa piletinom u kremastom sosu.', 750.00, 'main'),
    ('Republika Pub', 'Brownie', 'Čokoladni brownie sa prelivom.', 450.00, 'dessert'),
    ('Republika Pub', 'Chocolate Cake', 'Čokoladni kolač sa kremastim filom.', 290.00, 'dessert'),
    ('Republika Pub', 'Cheesecake', 'Kremasti cheesecake sa voćnim prelivom.', 320.00, 'dessert'),
    ('Republika Pub', 'Iced Tea', 'Hladan čaj sa limunom.', 180.00, 'drink'),
    ('Republika Pub', 'Orange Juice', 'Voćni sok od pomorandže.', 200.00, 'drink'),
    ('Republika Pub', 'Fresh Lemonade', 'Sveže ceđena limunada.', 220.00, 'drink'),
    ('Smash Burgers', 'Nachos', 'Tortilja čips sa sirom i salsom.', 390.00, 'appetizer'),
    ('Smash Burgers', 'Bruschetta', 'Prepečeni hleb sa paradajzom, bosiljkom i maslinovim uljem.', 450.00, 'appetizer'),
    ('Smash Burgers', 'BBQ Ribs', 'Sporo pečena rebra sa BBQ sosom i krompirom.', 650.00, 'main'),
    ('Smash Burgers', 'Fish & Chips', 'Pohovana riba sa pomfritom i tartar sosom.', 690.00, 'main'),
    ('Smash Burgers', 'Chicken Wrap', 'Tortilja sa piletinom, povrćem i sosom.', 750.00, 'main'),
    ('Smash Burgers', 'Vegetable Pasta', 'Pasta sa sezonskim povrćem i paradajz sosom.', 790.00, 'main'),
    ('Smash Burgers', 'Classic Burger', 'Goveđi burger sa sirom, povrćem i pomfritom.', 850.00, 'main'),
    ('Smash Burgers', 'Chicken Burger', 'Pileći burger sa salatom, sosom i pomfritom.', 890.00, 'main'),
    ('Smash Burgers', 'Double Smash Burger', 'Dupla smash pljeskavica sa sirom i sosom.', 950.00, 'main'),
    ('Smash Burgers', 'Apple Pie', 'Pita sa jabukama i cimetom.', 450.00, 'dessert'),
    ('Smash Burgers', 'Brownie', 'Čokoladni brownie sa prelivom.', 290.00, 'dessert'),
    ('Smash Burgers', 'Chocolate Cake', 'Čokoladni kolač sa kremastim filom.', 320.00, 'dessert'),
    ('Smash Burgers', 'Cola 0.33l', 'Gazirano bezalkoholno piće.', 160.00, 'drink'),
    ('Smash Burgers', 'Espresso', 'Espresso kafa.', 180.00, 'drink'),
    ('Smash Burgers', 'Mineralna voda 0.33l', 'Mineralna voda.', 200.00, 'drink'),
    ('Funk & Soul Pub', 'Onion Rings', 'Hrskavi kolutovi luka sa dip sosom.', 550.00, 'appetizer'),
    ('Funk & Soul Pub', 'Caesar Salad', 'Rimska salata, parmezan, krutoni i Caesar dresing.', 590.00, 'appetizer'),
    ('Funk & Soul Pub', 'Mozzarella Sticks', 'Pohovani mozzarella štapići sa dip sosom.', 350.00, 'appetizer'),
    ('Funk & Soul Pub', 'Classic Burger', 'Goveđi burger sa sirom, povrćem i pomfritom.', 990.00, 'main'),
    ('Funk & Soul Pub', 'Chicken Burger', 'Pileći burger sa salatom, sosom i pomfritom.', 1090.00, 'main'),
    ('Funk & Soul Pub', 'Double Smash Burger', 'Dupla smash pljeskavica sa sirom i sosom.', 1190.00, 'main'),
    ('Funk & Soul Pub', 'Club Sandwich', 'Sendvič sa piletinom, slaninom, salatom i pomfritom.', 650.00, 'main'),
    ('Funk & Soul Pub', 'Grilled Chicken', 'Pileći file sa grilovanim povrćem i krompirom.', 690.00, 'main'),
    ('Funk & Soul Pub', 'Penne Chicken', 'Penne pasta sa piletinom u kremastom sosu.', 750.00, 'main'),
    ('Funk & Soul Pub', 'Cheesecake', 'Kremasti cheesecake sa voćnim prelivom.', 450.00, 'dessert'),
    ('Funk & Soul Pub', 'Pancakes', 'Palačinke sa kremom i sezonskim voćem.', 290.00, 'dessert'),
    ('Funk & Soul Pub', 'Apple Pie', 'Pita sa jabukama i cimetom.', 320.00, 'dessert'),
    ('Funk & Soul Pub', 'Cola 0.33l', 'Gazirano bezalkoholno piće.', 250.00, 'drink'),
    ('Funk & Soul Pub', 'Espresso', 'Espresso kafa.', 290.00, 'drink'),
    ('Funk & Soul Pub', 'Mineralna voda 0.33l', 'Mineralna voda.', 160.00, 'drink'),
    ('Funk & Soul Pub', 'Iced Tea', 'Hladan čaj sa limunom.', 180.00, 'drink'),
    ('Two Guys Smash Burger', 'Chicken Wings', 'Hrskava pileća krilca sa sosom.', 390.00, 'appetizer'),
    ('Two Guys Smash Burger', 'Onion Rings', 'Hrskavi kolutovi luka sa dip sosom.', 450.00, 'appetizer'),
    ('Two Guys Smash Burger', 'Caesar Salad', 'Rimska salata, parmezan, krutoni i Caesar dresing.', 490.00, 'appetizer'),
    ('Two Guys Smash Burger', 'Mozzarella Sticks', 'Pohovani mozzarella štapići sa dip sosom.', 550.00, 'appetizer'),
    ('Two Guys Smash Burger', 'Nachos', 'Tortilja čips sa sirom i salsom.', 590.00, 'appetizer'),
    ('Two Guys Smash Burger', 'Club Sandwich', 'Sendvič sa piletinom, slaninom, salatom i pomfritom.', 1190.00, 'main'),
    ('Two Guys Smash Burger', 'Grilled Chicken', 'Pileći file sa grilovanim povrćem i krompirom.', 650.00, 'main'),
    ('Two Guys Smash Burger', 'Penne Chicken', 'Penne pasta sa piletinom u kremastom sosu.', 690.00, 'main'),
    ('Two Guys Smash Burger', 'BBQ Ribs', 'Sporo pečena rebra sa BBQ sosom i krompirom.', 750.00, 'main'),
    ('Two Guys Smash Burger', 'Fish & Chips', 'Pohovana riba sa pomfritom i tartar sosom.', 790.00, 'main'),
    ('Two Guys Smash Burger', 'Chicken Wrap', 'Tortilja sa piletinom, povrćem i sosom.', 850.00, 'main'),
    ('Two Guys Smash Burger', 'Chocolate Cake', 'Čokoladni kolač sa kremastim filom.', 290.00, 'dessert'),
    ('Two Guys Smash Burger', 'Cheesecake', 'Kremasti cheesecake sa voćnim prelivom.', 320.00, 'dessert'),
    ('Two Guys Smash Burger', 'Pancakes', 'Palačinke sa kremom i sezonskim voćem.', 350.00, 'dessert'),
    ('Two Guys Smash Burger', 'Mineralna voda 0.33l', 'Mineralna voda.', 160.00, 'drink'),
    ('Two Guys Smash Burger', 'Iced Tea', 'Hladan čaj sa limunom.', 180.00, 'drink'),
    ('Two Guys Smash Burger', 'Orange Juice', 'Voćni sok od pomorandže.', 200.00, 'drink'),
    ('Punch Ramen', 'Miso Soup', 'Tradicionalna miso supa sa tofuom i algama.', 790.00, 'appetizer'),
    ('Punch Ramen', 'Chicken Karaage', 'Hrskava marinirana japanska piletina.', 890.00, 'appetizer'),
    ('Punch Ramen', 'Seaweed Salad', 'Salata od morskih algi sa susamom.', 550.00, 'appetizer'),
    ('Punch Ramen', 'Tempura Vegetables', 'Povrće u laganom tempura testu.', 590.00, 'appetizer'),
    ('Punch Ramen', 'Teriyaki Chicken Bowl', 'Piletina u teriyaki sosu sa pirinčem i povrćem.', 1790.00, 'main'),
    ('Punch Ramen', 'Beef Yakisoba', 'Pržene nudle sa govedinom i povrćem.', 950.00, 'main'),
    ('Punch Ramen', 'Vegetable Ramen', 'Ramen sa povrćem i aromatičnim bujonom.', 990.00, 'main'),
    ('Punch Ramen', 'Salmon Sushi Set', 'Izbor nigiri i maki sušija sa lososom.', 1090.00, 'main'),
    ('Punch Ramen', 'Spicy Tuna Roll', 'Maki rolnice sa tunjevinom i pikantnim sosom.', 1190.00, 'main'),
    ('Punch Ramen', 'California Roll', 'Rolnice sa surimijem, avokadom i krastavcem.', 1290.00, 'main'),
    ('Punch Ramen', 'Salmon Avocado Roll', 'Rolnice sa lososom i avokadom.', 1390.00, 'main'),
    ('Punch Ramen', 'Matcha Cheesecake', 'Kremasti cheesecake sa matcha čajem.', 490.00, 'dessert'),
    ('Punch Ramen', 'Dorayaki', 'Japanske palačinkice punjene slatkim kremom.', 520.00, 'dessert'),
    ('Punch Ramen', 'Sesame Ice Cream', 'Sladoled sa crnim susamom.', 590.00, 'dessert'),
    ('Punch Ramen', 'Mineralna voda 0.33l', 'Mineralna voda.', 220.00, 'drink'),
    ('Punch Ramen', 'Iced Green Tea', 'Hladan zeleni čaj.', 250.00, 'drink'),
    ('Punch Ramen', 'Ginger Lemonade', 'Limunada sa đumbirom.', 290.00, 'drink'),
    ('Super Vok Terazije', 'Spring Rolls', 'Hrskave prolećne rolnice sa povrćem.', 590.00, 'appetizer'),
    ('Super Vok Terazije', 'Wonton Soup', 'Bistra supa sa punjenim wonton knedlama.', 350.00, 'appetizer'),
    ('Super Vok Terazije', 'Cucumber Salad', 'Krastavac sa susamom, soja sosom i blagim čilijem.', 390.00, 'appetizer'),
    ('Super Vok Terazije', 'Hot & Sour Soup', 'Pikantno-kisela supa sa povrćem.', 450.00, 'appetizer'),
    ('Super Vok Terazije', 'Spicy Chicken Noodles', 'Pikantne nudle sa piletinom i povrćem.', 990.00, 'main'),
    ('Super Vok Terazije', 'Chicken Chow Mein', 'Pržene nudle sa piletinom i povrćem.', 1090.00, 'main'),
    ('Super Vok Terazije', 'Beef Noodles', 'Nudle sa govedinom, povrćem i soja sosom.', 1190.00, 'main'),
    ('Super Vok Terazije', 'Sweet & Sour Chicken', 'Piletina u slatko-kiselom sosu sa pirinčem.', 650.00, 'main'),
    ('Super Vok Terazije', 'Kung Pao Chicken', 'Piletina sa povrćem, kikirikijem i pikantnim sosom.', 690.00, 'main'),
    ('Super Vok Terazije', 'Vegetable Fried Rice', 'Prženi pirinač sa povrćem i jajetom.', 750.00, 'main'),
    ('Super Vok Terazije', 'Beef Black Pepper', 'Govedina sa povrćem i sosom od crnog bibera.', 790.00, 'main'),
    ('Super Vok Terazije', 'Sesame Balls', 'Kuglice od pirinčanog testa sa susamom.', 390.00, 'dessert'),
    ('Super Vok Terazije', 'Mango Pudding', 'Lagani puding od manga.', 450.00, 'dessert'),
    ('Super Vok Terazije', 'Coconut Ice Cream', 'Sladoled sa ukusom kokosa.', 290.00, 'dessert'),
    ('Super Vok Terazije', 'Mineralna voda 0.33l', 'Mineralna voda.', 200.00, 'drink'),
    ('Super Vok Terazije', 'Green Tea', 'Topao zeleni čaj.', 220.00, 'drink'),
    ('Super Vok Terazije', 'Orange Juice', 'Voćni sok od pomorandže.', 250.00, 'drink'),
    ('Super Vok Bulevar', 'Chicken Dumplings', 'Knedle punjene piletinom i povrćem.', 450.00, 'appetizer'),
    ('Super Vok Bulevar', 'Crispy Wontons', 'Prženi wontoni sa slatko-kiselim sosom.', 490.00, 'appetizer'),
    ('Super Vok Bulevar', 'Chicken Fried Rice', 'Prženi pirinač sa piletinom, povrćem i jajetom.', 650.00, 'main'),
    ('Super Vok Bulevar', 'Beef with Broccoli', 'Govedina sa brokolijem i soja sosom.', 690.00, 'main'),
    ('Super Vok Bulevar', 'Vegetable Chow Mein', 'Pržene nudle sa povrćem.', 750.00, 'main'),
    ('Super Vok Bulevar', 'Spicy Chicken Noodles', 'Pikantne nudle sa piletinom i povrćem.', 790.00, 'main'),
    ('Super Vok Bulevar', 'Chicken Chow Mein', 'Pržene nudle sa piletinom i povrćem.', 850.00, 'main'),
    ('Super Vok Bulevar', 'Beef Noodles', 'Nudle sa govedinom, povrćem i soja sosom.', 890.00, 'main'),
    ('Super Vok Bulevar', 'Sweet & Sour Chicken', 'Piletina u slatko-kiselom sosu sa pirinčem.', 950.00, 'main'),
    ('Super Vok Bulevar', 'Fried Pineapple', 'Prženi ananas sa medom i susamom.', 350.00, 'dessert'),
    ('Super Vok Bulevar', 'Fried Banana', 'Pržena banana sa medom.', 390.00, 'dessert'),
    ('Super Vok Bulevar', 'Sesame Balls', 'Kuglice od pirinčanog testa sa susamom.', 450.00, 'dessert'),
    ('Super Vok Bulevar', 'Lemon Iced Tea', 'Hladan čaj sa limunom.', 250.00, 'drink'),
    ('Super Vok Bulevar', 'Cola 0.33l', 'Gazirano bezalkoholno piće.', 290.00, 'drink'),
    ('Super Vok Bulevar', 'Mineralna voda 0.33l', 'Mineralna voda.', 160.00, 'drink'),
    ('Bad Ramen', 'Tempura Vegetables', 'Povrće u laganom tempura testu.', 590.00, 'appetizer'),
    ('Bad Ramen', 'Edamame', 'Kuvane mlade sojine mahune sa morskom solju.', 650.00, 'appetizer'),
    ('Bad Ramen', 'Gyoza', 'Japanske knedle punjene mesom i povrćem.', 690.00, 'appetizer'),
    ('Bad Ramen', 'Miso Ramen', 'Ramen u miso bujonu sa povrćem i jajetom.', 1790.00, 'main'),
    ('Bad Ramen', 'Tempura Udon', 'Udon nudle sa povrćem i tempura dodatkom.', 950.00, 'main'),
    ('Bad Ramen', 'Teriyaki Chicken Bowl', 'Piletina u teriyaki sosu sa pirinčem i povrćem.', 990.00, 'main'),
    ('Bad Ramen', 'Beef Yakisoba', 'Pržene nudle sa govedinom i povrćem.', 1090.00, 'main'),
    ('Bad Ramen', 'Vegetable Ramen', 'Ramen sa povrćem i aromatičnim bujonom.', 1190.00, 'main'),
    ('Bad Ramen', 'Salmon Sushi Set', 'Izbor nigiri i maki sušija sa lososom.', 1290.00, 'main'),
    ('Bad Ramen', 'Matcha Ice Cream', 'Sladoled sa ukusom matcha čaja.', 490.00, 'dessert'),
    ('Bad Ramen', 'Mochi Selection', 'Izbor japanskih mochi kolačića.', 520.00, 'dessert'),
    ('Bad Ramen', 'Matcha Cheesecake', 'Kremasti cheesecake sa matcha čajem.', 590.00, 'dessert'),
    ('Bad Ramen', 'Iced Green Tea', 'Hladan zeleni čaj.', 390.00, 'drink'),
    ('Bad Ramen', 'Ginger Lemonade', 'Limunada sa đumbirom.', 220.00, 'drink'),
    ('Bad Ramen', 'Green Tea', 'Topao japanski zeleni čaj.', 250.00, 'drink'),
    ('Zavičaj Balkanska', 'Lepinja sa kajmakom', 'Topla lepinja sa domaćim kajmakom.', 590.00, 'appetizer'),
    ('Zavičaj Balkanska', 'Šopska salata', 'Paradajz, krastavac, paprika, luk i beli sir.', 650.00, 'appetizer'),
    ('Zavičaj Balkanska', 'Domaća proja', 'Proja od kukuruznog brašna sa sirom.', 690.00, 'appetizer'),
    ('Zavičaj Balkanska', 'Leskovački uštipci', 'Pikantni mesni uštipci sa sirom i slaninom.', 950.00, 'main'),
    ('Zavičaj Balkanska', 'Pileći file na žaru', 'Pileći file sa grilovanim povrćem i krompirom.', 990.00, 'main'),
    ('Zavičaj Balkanska', 'Mućkalica', 'Dinstano meso sa paprikom, paradajzom i začinima.', 1090.00, 'main'),
    ('Zavičaj Balkanska', 'Punjena pljeskavica', 'Pljeskavica punjena sirom sa prilogom.', 1190.00, 'main'),
    ('Zavičaj Balkanska', 'Vešalica na žaru', 'Marinirana svinjska vešalica sa krompirom.', 1290.00, 'main'),
    ('Zavičaj Balkanska', 'Svinjski vrat na žaru', 'Svinjski vrat sa grilovanim povrćem.', 1390.00, 'main'),
    ('Zavičaj Balkanska', 'Palačinke sa kremom', 'Domaće palačinke sa kremom i mlevenim keksom.', 390.00, 'dessert'),
    ('Zavičaj Balkanska', 'Baklava', 'Tradicionalna baklava sa orasima i sirupom.', 450.00, 'dessert'),
    ('Zavičaj Balkanska', 'Orasnice', 'Domaći kolač od oraha.', 490.00, 'dessert'),
    ('Zavičaj Balkanska', 'Domaća limunada', 'Sveže ceđena limunada.', 390.00, 'drink'),
    ('Zavičaj Balkanska', 'Kisela voda 0.33l', 'Gazirana mineralna voda.', 220.00, 'drink'),
    ('Zavičaj Balkanska', 'Jogurt 0.25l', 'Hladan jogurt.', 250.00, 'drink'),
    ('Zavičaj Balkanska', 'Espresso', 'Kratka espresso kafa.', 290.00, 'drink'),
    ('Franš Restaurant', 'Bruschetta', 'Prepečeni hleb sa paradajzom, bosiljkom i maslinovim uljem.', 790.00, 'appetizer'),
    ('Franš Restaurant', 'Chicken Wings', 'Hrskava pileća krilca sa sosom.', 850.00, 'appetizer'),
    ('Franš Restaurant', 'Onion Rings', 'Hrskavi kolutovi luka sa dip sosom.', 890.00, 'appetizer'),
    ('Franš Restaurant', 'Chicken Burger', 'Pileći burger sa salatom, sosom i pomfritom.', 1890.00, 'main'),
    ('Franš Restaurant', 'Double Smash Burger', 'Dupla smash pljeskavica sa sirom i sosom.', 1990.00, 'main'),
    ('Franš Restaurant', 'Club Sandwich', 'Sendvič sa piletinom, slaninom, salatom i pomfritom.', 2190.00, 'main'),
    ('Franš Restaurant', 'Grilled Chicken', 'Pileći file sa grilovanim povrćem i krompirom.', 2290.00, 'main'),
    ('Franš Restaurant', 'Penne Chicken', 'Penne pasta sa piletinom u kremastom sosu.', 2490.00, 'main'),
    ('Franš Restaurant', 'Pancakes', 'Palačinke sa kremom i sezonskim voćem.', 550.00, 'dessert'),
    ('Franš Restaurant', 'Apple Pie', 'Pita sa jabukama i cimetom.', 590.00, 'dessert'),
    ('Franš Restaurant', 'Mineralna voda 0.33l', 'Mineralna voda.', 350.00, 'drink'),
    ('Franš Restaurant', 'Iced Tea', 'Hladan čaj sa limunom.', 390.00, 'drink'),
    ('Franš Restaurant', 'Orange Juice', 'Voćni sok od pomorandže.', 490.00, 'drink'),
    ('Mezestoran Dvorište', 'Greek Salad', 'Paradajz, krastavac, masline i feta sir.', 690.00, 'appetizer'),
    ('Mezestoran Dvorište', 'Hummus', 'Kremasti namaz od leblebija sa maslinovim uljem.', 790.00, 'appetizer'),
    ('Mezestoran Dvorište', 'Tzatziki', 'Jogurt, krastavac, beli luk i začinsko bilje.', 890.00, 'appetizer'),
    ('Mezestoran Dvorište', 'Grilled Halloumi', 'Grilovani halloumi sir sa maslinovim uljem.', 550.00, 'appetizer'),
    ('Mezestoran Dvorište', 'Vegetable Plate', 'Selekcija grilovanog mediteranskog povrća i sira.', 1090.00, 'main'),
    ('Mezestoran Dvorište', 'Grilled Salmon', 'Losos sa blitvom i limunom.', 1190.00, 'main'),
    ('Mezestoran Dvorište', 'Seafood Risotto', 'Rižoto sa morskim plodovima.', 1290.00, 'main'),
    ('Mezestoran Dvorište', 'Chicken Gyros Plate', 'Pileći gyros sa pitom, tzatzikijem i povrćem.', 1390.00, 'main'),
    ('Mezestoran Dvorište', 'Falafel Plate', 'Falafel sa hummusom, salatom i pita hlebom.', 1490.00, 'main'),
    ('Mezestoran Dvorište', 'Grilled Sea Bass', 'Brancin sa grilovanim povrćem i limunom.', 1590.00, 'main'),
    ('Mezestoran Dvorište', 'Chicken Souvlaki', 'Pileći ražnjići sa pita hlebom i tzatzikijem.', 1690.00, 'main'),
    ('Mezestoran Dvorište', 'Orange Cake', 'Sočan kolač od pomorandže.', 590.00, 'dessert'),
    ('Mezestoran Dvorište', 'Panna Cotta', 'Panna cotta sa sezonskim voćem.', 390.00, 'dessert'),
    ('Mezestoran Dvorište', 'Lemon Cake', 'Lagani kolač od limuna.', 450.00, 'dessert'),
    ('Mezestoran Dvorište', 'Mineralna voda 0.33l', 'Gazirana mineralna voda.', 290.00, 'drink'),
    ('Mezestoran Dvorište', 'Iced Tea', 'Hladan čaj sa citrusima.', 320.00, 'drink'),
    ('Mezestoran Dvorište', 'Espresso', 'Espresso kafa.', 350.00, 'drink'),
    ('Two Kings Restaurant by Hilton', 'Bruschetta', 'Prepečeni hleb sa paradajzom, bosiljkom i maslinovim uljem.', 790.00, 'appetizer'),
    ('Two Kings Restaurant by Hilton', 'Chicken Wings', 'Hrskava pileća krilca sa sosom.', 890.00, 'appetizer'),
    ('Two Kings Restaurant by Hilton', 'Onion Rings', 'Hrskavi kolutovi luka sa dip sosom.', 550.00, 'appetizer'),
    ('Two Kings Restaurant by Hilton', 'Caesar Salad', 'Rimska salata, parmezan, krutoni i Caesar dresing.', 590.00, 'appetizer'),
    ('Two Kings Restaurant by Hilton', 'Vegetable Pasta', 'Pasta sa sezonskim povrćem i paradajz sosom.', 1290.00, 'main'),
    ('Two Kings Restaurant by Hilton', 'Classic Burger', 'Goveđi burger sa sirom, povrćem i pomfritom.', 1390.00, 'main'),
    ('Two Kings Restaurant by Hilton', 'Chicken Burger', 'Pileći burger sa salatom, sosom i pomfritom.', 1490.00, 'main'),
    ('Two Kings Restaurant by Hilton', 'Double Smash Burger', 'Dupla smash pljeskavica sa sirom i sosom.', 1590.00, 'main'),
    ('Two Kings Restaurant by Hilton', 'Club Sandwich', 'Sendvič sa piletinom, slaninom, salatom i pomfritom.', 1690.00, 'main'),
    ('Two Kings Restaurant by Hilton', 'Grilled Chicken', 'Pileći file sa grilovanim povrćem i krompirom.', 1790.00, 'main'),
    ('Two Kings Restaurant by Hilton', 'Chocolate Cake', 'Čokoladni kolač sa kremastim filom.', 450.00, 'dessert'),
    ('Two Kings Restaurant by Hilton', 'Cheesecake', 'Kremasti cheesecake sa voćnim prelivom.', 490.00, 'dessert'),
    ('Two Kings Restaurant by Hilton', 'Pancakes', 'Palačinke sa kremom i sezonskim voćem.', 520.00, 'dessert'),
    ('Two Kings Restaurant by Hilton', 'Orange Juice', 'Voćni sok od pomorandže.', 320.00, 'drink'),
    ('Two Kings Restaurant by Hilton', 'Fresh Lemonade', 'Sveže ceđena limunada.', 350.00, 'drink'),
    ('Two Kings Restaurant by Hilton', 'Cola 0.33l', 'Gazirano bezalkoholno piće.', 390.00, 'drink'),
    ('Two Kings Restaurant by Hilton', 'Espresso', 'Espresso kafa.', 220.00, 'drink'),
    ('Mama Restaurant Belgrade', 'Onion Rings', 'Hrskavi kolutovi luka sa dip sosom.', 790.00, 'appetizer'),
    ('Mama Restaurant Belgrade', 'Caesar Salad', 'Rimska salata, parmezan, krutoni i Caesar dresing.', 890.00, 'appetizer'),
    ('Mama Restaurant Belgrade', 'Mozzarella Sticks', 'Pohovani mozzarella štapići sa dip sosom.', 550.00, 'appetizer'),
    ('Mama Restaurant Belgrade', 'Vegetable Pasta', 'Pasta sa sezonskim povrćem i paradajz sosom.', 1690.00, 'main'),
    ('Mama Restaurant Belgrade', 'Classic Burger', 'Goveđi burger sa sirom, povrćem i pomfritom.', 1790.00, 'main'),
    ('Mama Restaurant Belgrade', 'Chicken Burger', 'Pileći burger sa salatom, sosom i pomfritom.', 950.00, 'main'),
    ('Mama Restaurant Belgrade', 'Double Smash Burger', 'Dupla smash pljeskavica sa sirom i sosom.', 990.00, 'main'),
    ('Mama Restaurant Belgrade', 'Club Sandwich', 'Sendvič sa piletinom, slaninom, salatom i pomfritom.', 1090.00, 'main'),
    ('Mama Restaurant Belgrade', 'Grilled Chicken', 'Pileći file sa grilovanim povrćem i krompirom.', 1190.00, 'main'),
    ('Mama Restaurant Belgrade', 'Apple Pie', 'Pita sa jabukama i cimetom.', 450.00, 'dessert'),
    ('Mama Restaurant Belgrade', 'Brownie', 'Čokoladni brownie sa prelivom.', 490.00, 'dessert'),
    ('Mama Restaurant Belgrade', 'Chocolate Cake', 'Čokoladni kolač sa kremastim filom.', 520.00, 'dessert'),
    ('Mama Restaurant Belgrade', 'Iced Tea', 'Hladan čaj sa limunom.', 250.00, 'drink'),
    ('Mama Restaurant Belgrade', 'Orange Juice', 'Voćni sok od pomorandže.', 290.00, 'drink'),
    ('Mama Restaurant Belgrade', 'Fresh Lemonade', 'Sveže ceđena limunada.', 320.00, 'drink'),
    ('Comunale Caffe e Cucina', 'Antipasto Misto', 'Izbor italijanskih sireva, povrća i suhomesnatih proizvoda.', 550.00, 'appetizer'),
    ('Comunale Caffe e Cucina', 'Bruschetta al Pomodoro', 'Prepečeni hleb, paradajz, beli luk, bosiljak i maslinovo ulje.', 590.00, 'appetizer'),
    ('Comunale Caffe e Cucina', 'Caprese', 'Paradajz, mozzarella, bosiljak i maslinovo ulje.', 650.00, 'appetizer'),
    ('Comunale Caffe e Cucina', 'Tagliatelle al Funghi', 'Tagliatelle sa pečurkama u kremastom sosu.', 1490.00, 'main'),
    ('Comunale Caffe e Cucina', 'Pizza Margherita', 'Paradajz sos, mozzarella i bosiljak.', 1590.00, 'main'),
    ('Comunale Caffe e Cucina', 'Pizza Diavola', 'Paradajz sos, mozzarella i pikantna salama.', 1690.00, 'main'),
    ('Comunale Caffe e Cucina', 'Pizza Quattro Formaggi', 'Pizza sa četiri vrste sira.', 1790.00, 'main'),
    ('Comunale Caffe e Cucina', 'Pizza Prosciutto e Funghi', 'Paradajz sos, mozzarella, šunka i pečurke.', 950.00, 'main'),
    ('Comunale Caffe e Cucina', 'Pizza Capricciosa', 'Paradajz sos, mozzarella, šunka, pečurke i masline.', 990.00, 'main'),
    ('Comunale Caffe e Cucina', 'Pizza Vegetariana', 'Paradajz sos, mozzarella i sezonsko povrće.', 1090.00, 'main'),
    ('Comunale Caffe e Cucina', 'Tiramisu', 'Klasični italijanski desert sa mascarpone kremom i kafom.', 450.00, 'dessert'),
    ('Comunale Caffe e Cucina', 'Panna Cotta', 'Panna cotta sa voćnim prelivom.', 490.00, 'dessert'),
    ('Comunale Caffe e Cucina', 'Espresso', 'Klasični italijanski espresso.', 320.00, 'drink'),
    ('Comunale Caffe e Cucina', 'Ledeni čaj', 'Hladan čaj sa limunom.', 350.00, 'drink'),
    ('Comunale Caffe e Cucina', 'Cappuccino', 'Espresso sa mlečnom penom.', 390.00, 'drink'),
    ('Tri šešira', 'Pečena paprika sa belim lukom', 'Pečena paprika sa uljem, peršunom i belim lukom.', 690.00, 'appetizer'),
    ('Tri šešira', 'Sir sa kajmakom', 'Izbor domaćeg sira i kajmaka.', 790.00, 'appetizer'),
    ('Tri šešira', 'Lepinja sa kajmakom', 'Topla lepinja sa domaćim kajmakom.', 890.00, 'appetizer'),
    ('Tri šešira', 'Šopska salata', 'Paradajz, krastavac, paprika, luk i beli sir.', 550.00, 'appetizer'),
    ('Tri šešira', 'Ćevapi sa kajmakom', 'Ćevapi sa lukom, lepinjom i kajmakom.', 950.00, 'main'),
    ('Tri šešira', 'Leskovačka pljeskavica', 'Začinjena pljeskavica sa prilogom i lepinjom.', 990.00, 'main'),
    ('Tri šešira', 'Karađorđeva šnicla', 'Punjena pohovana šnicla sa tartar sosom i prilogom.', 1090.00, 'main'),
    ('Tri šešira', 'Leskovački uštipci', 'Pikantni mesni uštipci sa sirom i slaninom.', 1190.00, 'main'),
    ('Tri šešira', 'Pileći file na žaru', 'Pileći file sa grilovanim povrćem i krompirom.', 1290.00, 'main'),
    ('Tri šešira', 'Mućkalica', 'Dinstano meso sa paprikom, paradajzom i začinima.', 1390.00, 'main'),
    ('Tri šešira', 'Punjena pljeskavica', 'Pljeskavica punjena sirom sa prilogom.', 1490.00, 'main'),
    ('Tri šešira', 'Pita sa jabukama', 'Topla pita sa jabukama i cimetom.', 390.00, 'dessert'),
    ('Tri šešira', 'Tufahija', 'Pečena jabuka punjena orasima.', 450.00, 'dessert'),
    ('Tri šešira', 'Palačinke sa kremom', 'Domaće palačinke sa kremom i mlevenim keksom.', 490.00, 'dessert'),
    ('Tri šešira', 'Domaća limunada', 'Sveže ceđena limunada.', 350.00, 'drink'),
    ('Tri šešira', 'Kisela voda 0.33l', 'Gazirana mineralna voda.', 390.00, 'drink'),
    ('Tri šešira', 'Jogurt 0.25l', 'Hladan jogurt.', 220.00, 'drink'),
    ('Steakhouse El Toro', 'Crispy Onion Rings', 'Hrskavi kolutovi luka sa sosom.', 790.00, 'appetizer'),
    ('Steakhouse El Toro', 'Caesar Salad', 'Rimska salata, parmezan, krutoni i Caesar dresing.', 850.00, 'appetizer'),
    ('Steakhouse El Toro', 'Chicken Wings', 'Pileća krilca sa blagim BBQ sosom.', 890.00, 'appetizer'),
    ('Steakhouse El Toro', 'Grilled Chicken Steak', 'Pileći steak sa povrćem i pečenim krompirom.', 1990.00, 'main'),
    ('Steakhouse El Toro', 'Pepper Steak', 'Goveđi steak sa kremastim sosom od bibera.', 2190.00, 'main'),
    ('Steakhouse El Toro', 'Surf & Turf', 'Goveđi steak sa gamborima i prilogom.', 2290.00, 'main'),
    ('Steakhouse El Toro', 'BBQ Chicken', 'Grilovana piletina sa BBQ sosom i krompirom.', 2490.00, 'main'),
    ('Steakhouse El Toro', 'Steak Sandwich', 'Goveđi steak u tostiranom pecivu sa povrćem.', 2690.00, 'main'),
    ('Steakhouse El Toro', 'Ribeye Steak', 'Grilovani ribeye steak sa krompirom i sosom.', 2990.00, 'main'),
    ('Steakhouse El Toro', 'Striploin Steak', 'Striploin steak sa grilovanim povrćem.', 3290.00, 'main'),
    ('Steakhouse El Toro', 'Apple Pie', 'Topla pita sa jabukama i cimetom.', 650.00, 'dessert'),
    ('Steakhouse El Toro', 'Vanilla Ice Cream', 'Sladoled od vanile sa prelivom.', 690.00, 'dessert'),
    ('Steakhouse El Toro', 'Tonic Water 0.25l', 'Gazirani tonic napitak.', 390.00, 'drink'),
    ('Steakhouse El Toro', 'Espresso', 'Espresso kafa.', 490.00, 'drink'),
    ('Steakhouse El Toro', 'Mineralna voda 0.33l', 'Mineralna voda.', 590.00, 'drink'),
    ('Lorenzo & Kakalamba', 'Bruschetta', 'Prepečeni hleb sa paradajzom, bosiljkom i maslinovim uljem.', 850.00, 'appetizer'),
    ('Lorenzo & Kakalamba', 'Chicken Wings', 'Hrskava pileća krilca sa sosom.', 890.00, 'appetizer'),
    ('Lorenzo & Kakalamba', 'Onion Rings', 'Hrskavi kolutovi luka sa dip sosom.', 990.00, 'appetizer'),
    ('Lorenzo & Kakalamba', 'Caesar Salad', 'Rimska salata, parmezan, krutoni i Caesar dresing.', 1090.00, 'appetizer'),
    ('Lorenzo & Kakalamba', 'BBQ Ribs', 'Sporo pečena rebra sa BBQ sosom i krompirom.', 2990.00, 'main'),
    ('Lorenzo & Kakalamba', 'Fish & Chips', 'Pohovana riba sa pomfritom i tartar sosom.', 3290.00, 'main'),
    ('Lorenzo & Kakalamba', 'Chicken Wrap', 'Tortilja sa piletinom, povrćem i sosom.', 1590.00, 'main'),
    ('Lorenzo & Kakalamba', 'Vegetable Pasta', 'Pasta sa sezonskim povrćem i paradajz sosom.', 1690.00, 'main'),
    ('Lorenzo & Kakalamba', 'Classic Burger', 'Goveđi burger sa sirom, povrćem i pomfritom.', 1890.00, 'main'),
    ('Lorenzo & Kakalamba', 'Chicken Burger', 'Pileći burger sa salatom, sosom i pomfritom.', 1990.00, 'main'),
    ('Lorenzo & Kakalamba', 'Brownie', 'Čokoladni brownie sa prelivom.', 650.00, 'dessert'),
    ('Lorenzo & Kakalamba', 'Chocolate Cake', 'Čokoladni kolač sa kremastim filom.', 690.00, 'dessert'),
    ('Lorenzo & Kakalamba', 'Cheesecake', 'Kremasti cheesecake sa voćnim prelivom.', 790.00, 'dessert'),
    ('Lorenzo & Kakalamba', 'Mineralna voda 0.33l', 'Mineralna voda.', 390.00, 'drink'),
    ('Lorenzo & Kakalamba', 'Iced Tea', 'Hladan čaj sa limunom.', 490.00, 'drink'),
    ('Lorenzo & Kakalamba', 'Orange Juice', 'Voćni sok od pomorandže.', 590.00, 'drink'),
    ('Lorenzo & Kakalamba', 'Fresh Lemonade', 'Sveže ceđena limunada.', 290.00, 'drink'),
    ('The View Rooftop', 'Nachos', 'Tortilja čips sa sirom i salsom.', 1090.00, 'appetizer'),
    ('The View Rooftop', 'Bruschetta', 'Prepečeni hleb sa paradajzom, bosiljkom i maslinovim uljem.', 1290.00, 'appetizer'),
    ('The View Rooftop', 'Chicken Wings', 'Hrskava pileća krilca sa sosom.', 790.00, 'appetizer'),
    ('The View Rooftop', 'BBQ Ribs', 'Sporo pečena rebra sa BBQ sosom i krompirom.', 2990.00, 'main'),
    ('The View Rooftop', 'Fish & Chips', 'Pohovana riba sa pomfritom i tartar sosom.', 3290.00, 'main'),
    ('The View Rooftop', 'Chicken Wrap', 'Tortilja sa piletinom, povrćem i sosom.', 1590.00, 'main'),
    ('The View Rooftop', 'Vegetable Pasta', 'Pasta sa sezonskim povrćem i paradajz sosom.', 1690.00, 'main'),
    ('The View Rooftop', 'Classic Burger', 'Goveđi burger sa sirom, povrćem i pomfritom.', 1890.00, 'main'),
    ('The View Rooftop', 'Cheesecake', 'Kremasti cheesecake sa voćnim prelivom.', 550.00, 'dessert'),
    ('The View Rooftop', 'Pancakes', 'Palačinke sa kremom i sezonskim voćem.', 590.00, 'dessert'),
    ('The View Rooftop', 'Mineralna voda 0.33l', 'Mineralna voda.', 390.00, 'drink'),
    ('The View Rooftop', 'Iced Tea', 'Hladan čaj sa limunom.', 490.00, 'drink'),
    ('The View Rooftop', 'Orange Juice', 'Voćni sok od pomorandže.', 590.00, 'drink'),
    ('Restoran Tri', 'Caesar Salad', 'Rimska salata, parmezan, krutoni i Caesar dresing.', 790.00, 'appetizer'),
    ('Restoran Tri', 'Mozzarella Sticks', 'Pohovani mozzarella štapići sa dip sosom.', 890.00, 'appetizer'),
    ('Restoran Tri', 'Nachos', 'Tortilja čips sa sirom i salsom.', 550.00, 'appetizer'),
    ('Restoran Tri', 'Chicken Burger', 'Pileći burger sa salatom, sosom i pomfritom.', 1090.00, 'main'),
    ('Restoran Tri', 'Double Smash Burger', 'Dupla smash pljeskavica sa sirom i sosom.', 1190.00, 'main'),
    ('Restoran Tri', 'Club Sandwich', 'Sendvič sa piletinom, slaninom, salatom i pomfritom.', 1290.00, 'main'),
    ('Restoran Tri', 'Grilled Chicken', 'Pileći file sa grilovanim povrćem i krompirom.', 1390.00, 'main'),
    ('Restoran Tri', 'Penne Chicken', 'Penne pasta sa piletinom u kremastom sosu.', 1490.00, 'main'),
    ('Restoran Tri', 'BBQ Ribs', 'Sporo pečena rebra sa BBQ sosom i krompirom.', 1590.00, 'main'),
    ('Restoran Tri', 'Pancakes', 'Palačinke sa kremom i sezonskim voćem.', 520.00, 'dessert'),
    ('Restoran Tri', 'Apple Pie', 'Pita sa jabukama i cimetom.', 590.00, 'dessert'),
    ('Restoran Tri', 'Brownie', 'Čokoladni brownie sa prelivom.', 390.00, 'dessert'),
    ('Restoran Tri', 'Iced Tea', 'Hladan čaj sa limunom.', 220.00, 'drink'),
    ('Restoran Tri', 'Orange Juice', 'Voćni sok od pomorandže.', 250.00, 'drink'),
    ('Restoran Tri', 'Fresh Lemonade', 'Sveže ceđena limunada.', 290.00, 'drink'),
    ('Jazz Restaurant', 'Chicken Wings', 'Hrskava pileća krilca sa sosom.', 550.00, 'appetizer'),
    ('Jazz Restaurant', 'Onion Rings', 'Hrskavi kolutovi luka sa dip sosom.', 590.00, 'appetizer'),
    ('Jazz Restaurant', 'Fish & Chips', 'Pohovana riba sa pomfritom i tartar sosom.', 1090.00, 'main'),
    ('Jazz Restaurant', 'Chicken Wrap', 'Tortilja sa piletinom, povrćem i sosom.', 1190.00, 'main'),
    ('Jazz Restaurant', 'Vegetable Pasta', 'Pasta sa sezonskim povrćem i paradajz sosom.', 650.00, 'main'),
    ('Jazz Restaurant', 'Classic Burger', 'Goveđi burger sa sirom, povrćem i pomfritom.', 690.00, 'main'),
    ('Jazz Restaurant', 'Chicken Burger', 'Pileći burger sa salatom, sosom i pomfritom.', 750.00, 'main'),
    ('Jazz Restaurant', 'Double Smash Burger', 'Dupla smash pljeskavica sa sirom i sosom.', 790.00, 'main'),
    ('Jazz Restaurant', 'Club Sandwich', 'Sendvič sa piletinom, slaninom, salatom i pomfritom.', 850.00, 'main'),
    ('Jazz Restaurant', 'Pancakes', 'Palačinke sa kremom i sezonskim voćem.', 350.00, 'dessert'),
    ('Jazz Restaurant', 'Apple Pie', 'Pita sa jabukama i cimetom.', 390.00, 'dessert'),
    ('Jazz Restaurant', 'Brownie', 'Čokoladni brownie sa prelivom.', 450.00, 'dessert'),
    ('Jazz Restaurant', 'Cola 0.33l', 'Gazirano bezalkoholno piće.', 200.00, 'drink'),
    ('Jazz Restaurant', 'Espresso', 'Espresso kafa.', 220.00, 'drink'),
    ('Jazz Restaurant', 'Mineralna voda 0.33l', 'Mineralna voda.', 250.00, 'drink'),
    ('Restoran Caruso', 'Onion Rings', 'Hrskavi kolutovi luka sa dip sosom.', 590.00, 'appetizer'),
    ('Restoran Caruso', 'Caesar Salad', 'Rimska salata, parmezan, krutoni i Caesar dresing.', 650.00, 'appetizer'),
    ('Restoran Caruso', 'Mozzarella Sticks', 'Pohovani mozzarella štapići sa dip sosom.', 690.00, 'appetizer'),
    ('Restoran Caruso', 'Double Smash Burger', 'Dupla smash pljeskavica sa sirom i sosom.', 1490.00, 'main'),
    ('Restoran Caruso', 'Club Sandwich', 'Sendvič sa piletinom, slaninom, salatom i pomfritom.', 1590.00, 'main'),
    ('Restoran Caruso', 'Grilled Chicken', 'Pileći file sa grilovanim povrćem i krompirom.', 1690.00, 'main'),
    ('Restoran Caruso', 'Penne Chicken', 'Penne pasta sa piletinom u kremastom sosu.', 1790.00, 'main'),
    ('Restoran Caruso', 'BBQ Ribs', 'Sporo pečena rebra sa BBQ sosom i krompirom.', 950.00, 'main'),
    ('Restoran Caruso', 'Fish & Chips', 'Pohovana riba sa pomfritom i tartar sosom.', 990.00, 'main'),
    ('Restoran Caruso', 'Cheesecake', 'Kremasti cheesecake sa voćnim prelivom.', 490.00, 'dessert'),
    ('Restoran Caruso', 'Pancakes', 'Palačinke sa kremom i sezonskim voćem.', 520.00, 'dessert'),
    ('Restoran Caruso', 'Apple Pie', 'Pita sa jabukama i cimetom.', 590.00, 'dessert'),
    ('Restoran Caruso', 'Mineralna voda 0.33l', 'Mineralna voda.', 390.00, 'drink'),
    ('Restoran Caruso', 'Iced Tea', 'Hladan čaj sa limunom.', 220.00, 'drink'),
    ('Restoran Caruso', 'Orange Juice', 'Voćni sok od pomorandže.', 250.00, 'drink'),
    ('Restoran Caruso', 'Fresh Lemonade', 'Sveže ceđena limunada.', 290.00, 'drink'),
    ('Restoran Enso', 'Bruschetta', 'Prepečeni hleb sa paradajzom, bosiljkom i maslinovim uljem.', 1290.00, 'appetizer'),
    ('Restoran Enso', 'Chicken Wings', 'Hrskava pileća krilca sa sosom.', 790.00, 'appetizer'),
    ('Restoran Enso', 'Onion Rings', 'Hrskavi kolutovi luka sa dip sosom.', 850.00, 'appetizer'),
    ('Restoran Enso', 'Caesar Salad', 'Rimska salata, parmezan, krutoni i Caesar dresing.', 890.00, 'appetizer'),
    ('Restoran Enso', 'Chicken Wrap', 'Tortilja sa piletinom, povrćem i sosom.', 1590.00, 'main'),
    ('Restoran Enso', 'Vegetable Pasta', 'Pasta sa sezonskim povrćem i paradajz sosom.', 1690.00, 'main'),
    ('Restoran Enso', 'Classic Burger', 'Goveđi burger sa sirom, povrćem i pomfritom.', 1890.00, 'main'),
    ('Restoran Enso', 'Chicken Burger', 'Pileći burger sa salatom, sosom i pomfritom.', 1990.00, 'main'),
    ('Restoran Enso', 'Double Smash Burger', 'Dupla smash pljeskavica sa sirom i sosom.', 2190.00, 'main'),
    ('Restoran Enso', 'Club Sandwich', 'Sendvič sa piletinom, slaninom, salatom i pomfritom.', 2290.00, 'main'),
    ('Restoran Enso', 'Cheesecake', 'Kremasti cheesecake sa voćnim prelivom.', 690.00, 'dessert'),
    ('Restoran Enso', 'Pancakes', 'Palačinke sa kremom i sezonskim voćem.', 790.00, 'dessert'),
    ('Restoran Enso', 'Apple Pie', 'Pita sa jabukama i cimetom.', 550.00, 'dessert'),
    ('Restoran Enso', 'Fresh Lemonade', 'Sveže ceđena limunada.', 390.00, 'drink'),
    ('Restoran Enso', 'Cola 0.33l', 'Gazirano bezalkoholno piće.', 490.00, 'drink'),
    ('Restoran Enso', 'Espresso', 'Espresso kafa.', 590.00, 'drink'),
    ('Restoran Enso', 'Mineralna voda 0.33l', 'Mineralna voda.', 290.00, 'drink'),
    ('Restoran Mihailo', 'Nachos', 'Tortilja čips sa sirom i salsom.', 690.00, 'appetizer'),
    ('Restoran Mihailo', 'Bruschetta', 'Prepečeni hleb sa paradajzom, bosiljkom i maslinovim uljem.', 790.00, 'appetizer'),
    ('Restoran Mihailo', 'Chicken Wrap', 'Tortilja sa piletinom, povrćem i sosom.', 1790.00, 'main'),
    ('Restoran Mihailo', 'Vegetable Pasta', 'Pasta sa sezonskim povrćem i paradajz sosom.', 950.00, 'main'),
    ('Restoran Mihailo', 'Classic Burger', 'Goveđi burger sa sirom, povrćem i pomfritom.', 990.00, 'main'),
    ('Restoran Mihailo', 'Chicken Burger', 'Pileći burger sa salatom, sosom i pomfritom.', 1090.00, 'main'),
    ('Restoran Mihailo', 'Double Smash Burger', 'Dupla smash pljeskavica sa sirom i sosom.', 1190.00, 'main'),
    ('Restoran Mihailo', 'Club Sandwich', 'Sendvič sa piletinom, slaninom, salatom i pomfritom.', 1290.00, 'main'),
    ('Restoran Mihailo', 'Grilled Chicken', 'Pileći file sa grilovanim povrćem i krompirom.', 1390.00, 'main'),
    ('Restoran Mihailo', 'Apple Pie', 'Pita sa jabukama i cimetom.', 590.00, 'dessert'),
    ('Restoran Mihailo', 'Brownie', 'Čokoladni brownie sa prelivom.', 390.00, 'dessert'),
    ('Restoran Mihailo', 'Chocolate Cake', 'Čokoladni kolač sa kremastim filom.', 450.00, 'dessert'),
    ('Restoran Mihailo', 'Fresh Lemonade', 'Sveže ceđena limunada.', 290.00, 'drink'),
    ('Restoran Mihailo', 'Cola 0.33l', 'Gazirano bezalkoholno piće.', 320.00, 'drink'),
    ('Restoran Mihailo', 'Espresso', 'Espresso kafa.', 350.00, 'drink'),
    ('April Beograd café & restaurant', 'Greek Salad', 'Paradajz, krastavac, masline i feta sir.', 590.00, 'appetizer'),
    ('April Beograd café & restaurant', 'Hummus', 'Kremasti namaz od leblebija sa maslinovim uljem.', 650.00, 'appetizer'),
    ('April Beograd café & restaurant', 'Tzatziki', 'Jogurt, krastavac, beli luk i začinsko bilje.', 690.00, 'appetizer'),
    ('April Beograd café & restaurant', 'Grilled Halloumi', 'Grilovani halloumi sir sa maslinovim uljem.', 790.00, 'appetizer'),
    ('April Beograd café & restaurant', 'Mediterranean Olives', 'Marinirane masline sa začinskim biljem.', 890.00, 'appetizer'),
    ('April Beograd café & restaurant', 'Chicken Gyros Plate', 'Pileći gyros sa pitom, tzatzikijem i povrćem.', 1090.00, 'main'),
    ('April Beograd café & restaurant', 'Falafel Plate', 'Falafel sa hummusom, salatom i pita hlebom.', 1190.00, 'main'),
    ('April Beograd café & restaurant', 'Grilled Sea Bass', 'Brancin sa grilovanim povrćem i limunom.', 1290.00, 'main'),
    ('April Beograd café & restaurant', 'Chicken Souvlaki', 'Pileći ražnjići sa pita hlebom i tzatzikijem.', 1390.00, 'main'),
    ('April Beograd café & restaurant', 'Seafood Pasta', 'Pasta sa morskim plodovima u laganom paradajz sosu.', 1490.00, 'main'),
    ('April Beograd café & restaurant', 'Moussaka', 'Zapečeno jelo sa patlidžanom, mesom i bešamelom.', 1590.00, 'main'),
    ('April Beograd café & restaurant', 'Baklava', 'Baklava sa orasima i mednim sirupom.', 390.00, 'dessert'),
    ('April Beograd café & restaurant', 'Greek Yogurt & Honey', 'Grčki jogurt sa medom i orasima.', 450.00, 'dessert'),
    ('April Beograd café & restaurant', 'Orange Cake', 'Sočan kolač od pomorandže.', 490.00, 'dessert'),
    ('April Beograd café & restaurant', 'Fresh Lemonade', 'Sveže ceđena limunada.', 320.00, 'drink'),
    ('April Beograd café & restaurant', 'Mineralna voda 0.33l', 'Gazirana mineralna voda.', 350.00, 'drink'),
    ('April Beograd café & restaurant', 'Iced Tea', 'Hladan čaj sa citrusima.', 390.00, 'drink'),
    ('Madera', 'Sir sa kajmakom', 'Izbor domaćeg sira i kajmaka.', 990.00, 'appetizer'),
    ('Madera', 'Lepinja sa kajmakom', 'Topla lepinja sa domaćim kajmakom.', 1090.00, 'appetizer'),
    ('Madera', 'Šopska salata', 'Paradajz, krastavac, paprika, luk i beli sir.', 1290.00, 'appetizer'),
    ('Madera', 'Punjena pljeskavica', 'Pljeskavica punjena sirom sa prilogom.', 2990.00, 'main'),
    ('Madera', 'Vešalica na žaru', 'Marinirana svinjska vešalica sa krompirom.', 3290.00, 'main'),
    ('Madera', 'Svinjski vrat na žaru', 'Svinjski vrat sa grilovanim povrćem.', 1590.00, 'main'),
    ('Madera', 'Pileći ražnjići', 'Pileći ražnjići sa povrćem i prilogom.', 1690.00, 'main'),
    ('Madera', 'Ćevapi sa kajmakom', 'Ćevapi sa lukom, lepinjom i kajmakom.', 1890.00, 'main'),
    ('Madera', 'Leskovačka pljeskavica', 'Začinjena pljeskavica sa prilogom i lepinjom.', 1990.00, 'main'),
    ('Madera', 'Karađorđeva šnicla', 'Punjena pohovana šnicla sa tartar sosom i prilogom.', 2190.00, 'main'),
    ('Madera', 'Orasnice', 'Domaći kolač od oraha.', 790.00, 'dessert'),
    ('Madera', 'Pita sa jabukama', 'Topla pita sa jabukama i cimetom.', 550.00, 'dessert'),
    ('Madera', 'Espresso', 'Kratka espresso kafa.', 590.00, 'drink'),
    ('Madera', 'Coca-Cola 0.33l', 'Gazirano bezalkoholno piće.', 290.00, 'drink'),
    ('Madera', 'Sok od pomorandže', 'Voćni sok od pomorandže.', 320.00, 'drink'),
    ('Trattoria Pepe', 'Focaccia', 'Pečena focaccia sa ruzmarinom i maslinovim uljem.', 790.00, 'appetizer'),
    ('Trattoria Pepe', 'Minestrone', 'Italijanska supa sa povrćem.', 890.00, 'appetizer'),
    ('Trattoria Pepe', 'Arancini', 'Hrskave kuglice od pirinča sa sirom.', 550.00, 'appetizer'),
    ('Trattoria Pepe', 'Spaghetti Carbonara', 'Pasta sa pancetom, jajetom, sirom i biberom.', 950.00, 'main'),
    ('Trattoria Pepe', 'Lasagne Bolognese', 'Zapečene lazanje sa ragù sosom i bešamelom.', 990.00, 'main'),
    ('Trattoria Pepe', 'Penne Arrabbiata', 'Penne u pikantnom paradajz sosu.', 1090.00, 'main'),
    ('Trattoria Pepe', 'Tagliatelle al Funghi', 'Tagliatelle sa pečurkama u kremastom sosu.', 1190.00, 'main'),
    ('Trattoria Pepe', 'Pizza Margherita', 'Paradajz sos, mozzarella i bosiljak.', 1290.00, 'main'),
    ('Trattoria Pepe', 'Pizza Diavola', 'Paradajz sos, mozzarella i pikantna salama.', 1390.00, 'main'),
    ('Trattoria Pepe', 'Affogato', 'Sladoled od vanile preliven espressom.', 390.00, 'dessert'),
    ('Trattoria Pepe', 'Tiramisu', 'Klasični italijanski desert sa mascarpone kremom i kafom.', 450.00, 'dessert'),
    ('Trattoria Pepe', 'Panna Cotta', 'Panna cotta sa voćnim prelivom.', 490.00, 'dessert'),
    ('Trattoria Pepe', 'Ledeni čaj', 'Hladan čaj sa limunom.', 220.00, 'drink'),
    ('Trattoria Pepe', 'Cappuccino', 'Espresso sa mlečnom penom.', 250.00, 'drink'),
    ('Trattoria Pepe', 'Sok od pomorandže', 'Voćni sok od pomorandže.', 290.00, 'drink'),
    ('Trattoria Pepe', 'Limonata', 'Italijanska limunada sa svežim limunom.', 320.00, 'drink'),
    ('Casa Nova', 'Bruschetta', 'Prepečeni hleb sa paradajzom, bosiljkom i maslinovim uljem.', 690.00, 'appetizer'),
    ('Casa Nova', 'Chicken Wings', 'Hrskava pileća krilca sa sosom.', 790.00, 'appetizer'),
    ('Casa Nova', 'Chicken Wrap', 'Tortilja sa piletinom, povrćem i sosom.', 1690.00, 'main'),
    ('Casa Nova', 'Vegetable Pasta', 'Pasta sa sezonskim povrćem i paradajz sosom.', 1790.00, 'main'),
    ('Casa Nova', 'Classic Burger', 'Goveđi burger sa sirom, povrćem i pomfritom.', 950.00, 'main'),
    ('Casa Nova', 'Chicken Burger', 'Pileći burger sa salatom, sosom i pomfritom.', 990.00, 'main'),
    ('Casa Nova', 'Double Smash Burger', 'Dupla smash pljeskavica sa sirom i sosom.', 1090.00, 'main'),
    ('Casa Nova', 'Club Sandwich', 'Sendvič sa piletinom, slaninom, salatom i pomfritom.', 1190.00, 'main'),
    ('Casa Nova', 'Grilled Chicken', 'Pileći file sa grilovanim povrćem i krompirom.', 1290.00, 'main'),
    ('Casa Nova', 'Brownie', 'Čokoladni brownie sa prelivom.', 450.00, 'dessert'),
    ('Casa Nova', 'Chocolate Cake', 'Čokoladni kolač sa kremastim filom.', 490.00, 'dessert'),
    ('Casa Nova', 'Cheesecake', 'Kremasti cheesecake sa voćnim prelivom.', 520.00, 'dessert'),
    ('Casa Nova', 'Fresh Lemonade', 'Sveže ceđena limunada.', 320.00, 'drink'),
    ('Casa Nova', 'Cola 0.33l', 'Gazirano bezalkoholno piće.', 350.00, 'drink'),
    ('Casa Nova', 'Espresso', 'Espresso kafa.', 390.00, 'drink'),
    ('Durmitor', 'Sir sa kajmakom', 'Izbor domaćeg sira i kajmaka.', 790.00, 'appetizer'),
    ('Durmitor', 'Lepinja sa kajmakom', 'Topla lepinja sa domaćim kajmakom.', 890.00, 'appetizer'),
    ('Durmitor', 'Šopska salata', 'Paradajz, krastavac, paprika, luk i beli sir.', 550.00, 'appetizer'),
    ('Durmitor', 'Domaća proja', 'Proja od kukuruznog brašna sa sirom.', 590.00, 'appetizer'),
    ('Durmitor', 'Leskovačka pljeskavica', 'Začinjena pljeskavica sa prilogom i lepinjom.', 1090.00, 'main'),
    ('Durmitor', 'Karađorđeva šnicla', 'Punjena pohovana šnicla sa tartar sosom i prilogom.', 1190.00, 'main'),
    ('Durmitor', 'Leskovački uštipci', 'Pikantni mesni uštipci sa sirom i slaninom.', 1290.00, 'main'),
    ('Durmitor', 'Pileći file na žaru', 'Pileći file sa grilovanim povrćem i krompirom.', 1390.00, 'main'),
    ('Durmitor', 'Mućkalica', 'Dinstano meso sa paprikom, paradajzom i začinima.', 1490.00, 'main'),
    ('Durmitor', 'Punjena pljeskavica', 'Pljeskavica punjena sirom sa prilogom.', 1590.00, 'main'),
    ('Durmitor', 'Tufahija', 'Pečena jabuka punjena orasima.', 590.00, 'dessert'),
    ('Durmitor', 'Palačinke sa kremom', 'Domaće palačinke sa kremom i mlevenim keksom.', 390.00, 'dessert'),
    ('Durmitor', 'Baklava', 'Tradicionalna baklava sa orasima i sirupom.', 450.00, 'dessert'),
    ('Durmitor', 'Kisela voda 0.33l', 'Gazirana mineralna voda.', 220.00, 'drink'),
    ('Durmitor', 'Jogurt 0.25l', 'Hladan jogurt.', 250.00, 'drink'),
    ('Durmitor', 'Espresso', 'Kratka espresso kafa.', 290.00, 'drink'),
    ('Durmitor', 'Coca-Cola 0.33l', 'Gazirano bezalkoholno piće.', 320.00, 'drink')
) AS v(restaurant_name, food_name, description, price, category)
INNER JOIN Restaurants r
    ON r.name = v.restaurant_name
WHERE NOT EXISTS (
    SELECT 1
    FROM MenuItems mi
    WHERE mi.restaurant_id = r.id
      AND mi.food_name = v.food_name
      AND mi.category = v.category
);