import type { Restaurant, Table, MenuItem } from "./types"

export const mockRestaurants: Restaurant[] = [
    {
      id: 1,
      name: "Pizza Palace",
      description: "Authentic Italian pizza with fresh ingredients bdhwecviw cbewibcfhwcb bchwbhv bdhqecviewvceyewgcyvchvwgvwuvyewvbcevbcwyivi",
      city: "Belgrade",
      address: "Knez Mihailova 12",
      phone_number: "+381 64 123 45 67",
      opening_time_workday: "10:00",
      closing_time_workday: "22:00",
      opening_time_weekend: "11:00",
      closing_time_weekend: "23:00",
      rating: 4.5,
      price_range: "$$",
      cusine_type: "Italian",
      reservation_duration: "03:00:00",
    },
    {
      id: 2,
      name: "Sushi Spot",
      description: "Fresh sushi prepared by expert chefs",
      city: "Novi Sad",
      address: "Zmaj Jovina 45",
      phone_number: "+381 63 987 65 43",
      opening_time_workday: "11:00",
      closing_time_workday: "21:00",
      opening_time_weekend: "12:00",
      closing_time_weekend: "22:00",
      rating: 4.8,
      price_range: "$$$",
      cusine_type: "Japanese",
      reservation_duration: "03:00:00",
    },
    {
      id: 3,
      name: "Balkan Bistro",
      description: "Traditional Balkan dishes in a cozy atmosphere",
      city: "Belgrade",
      address: "Kralja Petra 8",
      phone_number: "+381 65 555 44 33",
      opening_time_workday: "09:00",
      closing_time_workday: "23:00",
      opening_time_weekend: "10:00",
      closing_time_weekend: "23:30",
      rating: 4.2,
      price_range: "$$",
      cusine_type: "Balkan",
      reservation_duration: "03:00:00",
    },
    {
      id: 4,
      name: "Le Gourmet",
      description: "Fine dining French cuisine with wine pairing",
      city: "Novi Sad",
      address: "Bulevar Oslobođenja 15",
      phone_number: "+381 62 112 22 33",
      opening_time_workday: "12:00",
      closing_time_workday: "23:00",
      opening_time_weekend: "12:00",
      closing_time_weekend: "23:30",
      rating: 4.9,
      price_range: "$$$",
      cusine_type: "French",
      reservation_duration: "03:00:00",
    },
    {
      id: 5,
      name: "Mediterraneo",
      description: "Mediterranean flavors with a modern twist",
      city: "Belgrade",
      address: "Njegoševa 20",
      phone_number: "+381 64 777 88 99",
      opening_time_workday: "10:00",
      closing_time_workday: "22:30",
      opening_time_weekend: "11:00",
      closing_time_weekend: "23:00",
      rating: 4.6,
      price_range: "$$$",
      cusine_type: "Mediterranean",
      reservation_duration: "03:00:00",
    },
]

export const mockTables: Table[] = [
    { id: 1, restaurantId: 1, location: 'Inside', seats: 2, available_number: 2 },
    { id: 2, restaurantId: 1, location: 'Inside', seats: 4, available_number: 3 },
    { id: 3, restaurantId: 1, location: 'Outside', seats: 6, available_number: 4 },

    { id: 4, restaurantId: 2, location: 'Inside', seats: 2, available_number: 2 },
    { id: 5, restaurantId: 2, location: 'Outside', seats: 4, available_number: 4 },
    { id: 6, restaurantId: 2, location: 'Outside', seats: 6, available_number: 5 },

    { id: 7, restaurantId: 3, location: 'Inside', seats: 2, available_number: 0 },
    { id: 8, restaurantId: 3, location: 'Inside', seats: 4, available_number: 2 },
    { id: 9, restaurantId: 3, location: 'Outside', seats: 6, available_number: 6 },
]

export const mockMenuItems: MenuItem[] = [
    {
        id: 1,
        restaurant_id: 1,
        food_name: 'Margherita Pizza',
        description: 'Classic pizza with tomato, mozzarella and basil',
        price: 8.99,
        image: '', 
        category: 'main',
    },
    {
        id: 2,
        restaurant_id: 1,
        food_name: 'Caesar Salad',
        description: 'Romaine lettuce, croutons, parmesan, Caesar dressing',
        price: 6.5,
        image: '',
        category: 'Salad',
    },
    {
        id: 3,
        restaurant_id: 1,
        food_name: 'Spaghetti Carbonara',
        description: 'Pasta with eggs, parmesan, pancetta and pepper',
        price: 9.75,
        image: '',
        category: 'main',
    },

    {
        id: 4,
        restaurant_id: 2,
        food_name: 'Cheeseburger',
        description: 'Beef patty, cheddar cheese, lettuce, tomato, pickles',
        price: 7.5,
        image: '',
        category: 'main',
    },
    {
        id: 5,
        restaurant_id: 2,
        food_name: 'French Fries',
        description: 'Crispy golden fries with ketchup',
        price: 3.0,
        image: '',
        category: 'main',
    },
    {
        id: 6,
        restaurant_id: 2,
        food_name: 'Chicken Wings',
        description: 'Spicy grilled chicken wings with dipping sauce',
        price: 6.5,
        image: '',
        category: 'appetizer',
    },

    {
        id: 7,
        restaurant_id: 3,
        food_name: 'Sushi Platter',
        description: 'Assorted nigiri and maki rolls',
        price: 15.0,
        image: '',
        category: 'main',
    },
    {
        id: 8,
        restaurant_id: 3,
        food_name: 'Miso Soup',
        description: 'Traditional Japanese soup with tofu and seaweed',
        price: 4.0,
        image: '',
        category: 'Soup',
    },
    {
        id: 9,
        restaurant_id: 3,
        food_name: 'Green Tea Ice Cream',
        description: 'Creamy ice cream with matcha flavor',
        price: 5.0,
        image: '',
        category: 'dessert',
    },
]


