services:
  identity-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: rns-identity-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_strong_Password123!"
    ports:
      - "1435:1433"
    volumes:
      - identity_sql_data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "Your_strong_Password123!" -C -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 20

  identity-api:
    build:
      context: .
      dockerfile: backend/ReserveNServeBackend/Services/Identity/Identity.API/Dockerfile
    container_name: rns-identity-api
    depends_on:
      identity-db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__IdentityDb: "Server=identity-db,1433;Database=ReserveNServe.Identity;User Id=sa;Password=Your_strong_Password123!;TrustServerCertificate=True"
      Jwt__Issuer: "ReserveNServe.Identity"
      Jwt__Audience: "ReserveNServe.ApiClients"
      Jwt__Key: "DEV_ONLY_CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_32+_CHARS"
      Jwt__AccessTokenMinutes: "60"
      RefreshToken__ExpirationDays: "14"
    ports:
      - "8081:8080"

volumes:
  identity_sql_data: